// Kody tablic rejestracyjnych: jeden wpis na powiat albo miasto na prawach powiatu (dzielnice Warszawy osobno).
// Sprawdzone ze wzorcową listą kodów (AutoCentrum); nazwy powiatów według PRG.
// Pola: kod (główny), alt (inne kody tej samej jednostki), nazwa, typ (miasto|ziemski), woj, lat, lng, wiki, siedziba (miasto, w którym jest starostwo)
window.POWIATY = [
  // ========== PODLASKIE ==========
  {"kod": "BI", "nazwa": "Białystok", "typ": "miasto", "woj": "podlaskie", "lat": 53.1277, "lng": 23.147, "wiki": "Białystok"},
  {"kod": "BS", "nazwa": "Suwałki", "typ": "miasto", "woj": "podlaskie", "lat": 54.1028, "lng": 22.932, "wiki": "Suwałki"},
  {"kod": "BL", "nazwa": "Łomża", "typ": "miasto", "woj": "podlaskie", "lat": 53.1825, "lng": 22.0522, "wiki": "Łomża"},
  {"kod": "BAU", "nazwa": "powiat augustowski", "typ": "ziemski", "woj": "podlaskie", "lat": 53.7974, "lng": 23.1341, "wiki": "Powiat_augustowski", "siedziba": "Augustów"},
  {"kod": "BIA", "nazwa": "powiat białostocki", "typ": "ziemski", "woj": "podlaskie", "lat": 53.1174, "lng": 23.5566, "wiki": "Powiat_białostocki", "siedziba": "Białystok"},
  {"kod": "BBI", "nazwa": "powiat bielski", "typ": "ziemski", "woj": "podlaskie", "lat": 52.7463, "lng": 23.0044, "wiki": "Powiat_bielski", "siedziba": "Bielsk Podlaski"},
  {"kod": "BGR", "nazwa": "powiat grajewski", "typ": "ziemski", "woj": "podlaskie", "lat": 53.555, "lng": 22.4189, "wiki": "Powiat_grajewski", "siedziba": "Grajewo"},
  {"kod": "BHA", "nazwa": "powiat hajnowski", "typ": "ziemski", "woj": "podlaskie", "lat": 52.7084, "lng": 23.661, "wiki": "Powiat_hajnowski", "siedziba": "Hajnówka"},
  {"kod": "BKL", "nazwa": "powiat kolneński", "typ": "ziemski", "woj": "podlaskie", "lat": 53.392, "lng": 21.9588, "wiki": "Powiat_kolneński", "siedziba": "Kolno"},
  {"kod": "BMN", "nazwa": "powiat moniecki", "typ": "ziemski", "woj": "podlaskie", "lat": 53.4458, "lng": 22.8171, "wiki": "Powiat_moniecki", "siedziba": "Mońki"},
  {"kod": "BSE", "nazwa": "powiat sejneński", "typ": "ziemski", "woj": "podlaskie", "lat": 54.0956, "lng": 23.3121, "wiki": "Powiat_sejneński", "siedziba": "Sejny"},
  {"kod": "BSI", "nazwa": "powiat siemiatycki", "typ": "ziemski", "woj": "podlaskie", "lat": 52.4886, "lng": 22.8847, "wiki": "Powiat_siemiatycki", "siedziba": "Siemiatycze"},
  {"kod": "BSK", "nazwa": "powiat sokólski", "typ": "ziemski", "woj": "podlaskie", "lat": 53.4352, "lng": 23.3857, "wiki": "Powiat_sokólski", "siedziba": "Sokółka"},
  {"kod": "BSU", "nazwa": "powiat suwalski", "typ": "ziemski", "woj": "podlaskie", "lat": 54.1666, "lng": 22.8136, "wiki": "Powiat_suwalski", "siedziba": "Suwałki"},
  {"kod": "BWM", "nazwa": "powiat wysokomazowiecki", "typ": "ziemski", "woj": "podlaskie", "lat": 52.8646, "lng": 22.5204, "wiki": "Powiat_wysokomazowiecki", "siedziba": "Wysokie Mazowieckie"},
  {"kod": "BZA", "nazwa": "powiat zambrowski", "typ": "ziemski", "woj": "podlaskie", "lat": 53.0228, "lng": 22.248, "wiki": "Powiat_zambrowski", "siedziba": "Zambrów"},
  {"kod": "BLM", "nazwa": "powiat łomżyński", "typ": "ziemski", "woj": "podlaskie", "lat": 53.2082, "lng": 22.2777, "wiki": "Powiat_łomżyński", "siedziba": "Łomża"},
  // ========== KUJAWSKO-POMORSKIE ==========
  {"kod": "CB", "nazwa": "Bydgoszcz", "typ": "miasto", "woj": "kujawsko-pomorskie", "lat": 53.1298, "lng": 18.0293, "wiki": "Bydgoszcz"},
  {"kod": "CG", "nazwa": "Grudziądz", "typ": "miasto", "woj": "kujawsko-pomorskie", "lat": 53.4725, "lng": 18.7619, "wiki": "Grudziądz"},
  {"kod": "CT", "nazwa": "Toruń", "typ": "miasto", "woj": "kujawsko-pomorskie", "lat": 53.0145, "lng": 18.5965, "wiki": "Toruń"},
  {"kod": "CW", "nazwa": "Włocławek", "typ": "miasto", "woj": "kujawsko-pomorskie", "lat": 52.6655, "lng": 19.0961, "wiki": "Włocławek"},
  {"kod": "CAL", "nazwa": "powiat aleksandrowski", "typ": "ziemski", "woj": "kujawsko-pomorskie", "lat": 52.7844, "lng": 18.7806, "wiki": "Powiat_aleksandrowski", "siedziba": "Aleksandrów Kujawski"},
  {"kod": "CBR", "nazwa": "powiat brodnicki", "typ": "ziemski", "woj": "kujawsko-pomorskie", "lat": 53.2698, "lng": 19.4132, "wiki": "Powiat_brodnicki", "siedziba": "Brodnica"},
  {"kod": "CBY", "nazwa": "powiat bydgoski", "typ": "ziemski", "woj": "kujawsko-pomorskie", "lat": 53.1921, "lng": 17.8255, "wiki": "Powiat_bydgoski", "siedziba": "Bydgoszcz"},
  {"kod": "CCH", "nazwa": "powiat chełmiński", "typ": "ziemski", "woj": "kujawsko-pomorskie", "lat": 53.3008, "lng": 18.5337, "wiki": "Powiat_chełmiński", "siedziba": "Chełmno"},
  {"kod": "CGD", "nazwa": "powiat golubsko-dobrzyński", "typ": "ziemski", "woj": "kujawsko-pomorskie", "lat": 53.0992, "lng": 19.0248, "wiki": "Powiat_golubsko-dobrzyński", "siedziba": "Golub-Dobrzyń"},
  {"kod": "CGR", "nazwa": "powiat grudziądzki", "typ": "ziemski", "woj": "kujawsko-pomorskie", "lat": 53.4715, "lng": 19.0124, "wiki": "Powiat_grudziądzki", "siedziba": "Grudziądz"},
  {"kod": "CIN", "nazwa": "powiat inowrocławski", "typ": "ziemski", "woj": "kujawsko-pomorskie", "lat": 52.7646, "lng": 18.3244, "wiki": "Powiat_inowrocławski", "siedziba": "Inowrocław"},
  {"kod": "CLI", "nazwa": "powiat lipnowski", "typ": "ziemski", "woj": "kujawsko-pomorskie", "lat": 52.8158, "lng": 19.1697, "wiki": "Powiat_lipnowski", "siedziba": "Lipno"},
  {"kod": "CMG", "nazwa": "powiat mogileński", "typ": "ziemski", "woj": "kujawsko-pomorskie", "lat": 52.6617, "lng": 18.0228, "wiki": "Powiat_mogileński", "siedziba": "Mogilno"},
  {"kod": "CNA", "nazwa": "powiat nakielski", "typ": "ziemski", "woj": "kujawsko-pomorskie", "lat": 53.0949, "lng": 17.5974, "wiki": "Powiat_nakielski", "siedziba": "Nakło nad Notecią"},
  {"kod": "CRA", "nazwa": "powiat radziejowski", "typ": "ziemski", "woj": "kujawsko-pomorskie", "lat": 52.5738, "lng": 18.597, "wiki": "Powiat_radziejowski", "siedziba": "Radziejów"},
  {"kod": "CRY", "nazwa": "powiat rypiński", "typ": "ziemski", "woj": "kujawsko-pomorskie", "lat": 53.0725, "lng": 19.4399, "wiki": "Powiat_rypiński", "siedziba": "Rypin"},
  {"kod": "CSE", "nazwa": "powiat sępoleński", "typ": "ziemski", "woj": "kujawsko-pomorskie", "lat": 53.4427, "lng": 17.5333, "wiki": "Powiat_sępoleński", "siedziba": "Sępólno Krajeńskie"},
  {"kod": "CSW", "nazwa": "powiat świecki", "typ": "ziemski", "woj": "kujawsko-pomorskie", "lat": 53.4809, "lng": 18.4269, "wiki": "Powiat_świecki", "siedziba": "Świecie"},
  {"kod": "CTR", "nazwa": "powiat toruński", "typ": "ziemski", "woj": "kujawsko-pomorskie", "lat": 53.0468, "lng": 18.4589, "wiki": "Powiat_toruński", "siedziba": "Toruń"},
  {"kod": "CTU", "nazwa": "powiat tucholski", "typ": "ziemski", "woj": "kujawsko-pomorskie", "lat": 53.5816, "lng": 17.9249, "wiki": "Powiat_tucholski", "siedziba": "Tuchola"},
  {"kod": "CWA", "nazwa": "powiat wąbrzeski", "typ": "ziemski", "woj": "kujawsko-pomorskie", "lat": 53.2824, "lng": 18.9281, "wiki": "Powiat_wąbrzeski", "siedziba": "Wąbrzeźno"},
  {"kod": "CWL", "nazwa": "powiat włocławski", "typ": "ziemski", "woj": "kujawsko-pomorskie", "lat": 52.5566, "lng": 19.0419, "wiki": "Powiat_włocławski", "siedziba": "Włocławek"},
  {"kod": "CZN", "nazwa": "powiat żniński", "typ": "ziemski", "woj": "kujawsko-pomorskie", "lat": 52.8224, "lng": 17.6907, "wiki": "Powiat_żniński", "siedziba": "Żnin"},
  // ========== DOLNOŚLĄSKIE ==========
  {"kod": "DJ", "nazwa": "Jelenia Góra", "typ": "miasto", "woj": "dolnośląskie", "lat": 50.8503, "lng": 15.654, "wiki": "Jelenia_Góra"},
  {"kod": "DL", "nazwa": "Legnica", "typ": "miasto", "woj": "dolnośląskie", "lat": 51.2047, "lng": 16.1746, "wiki": "Legnica"},
  {"kod": "DB", "nazwa": "Wałbrzych", "typ": "miasto", "woj": "dolnośląskie", "lat": 50.7852, "lng": 16.2846, "wiki": "Wałbrzych"},
  {"kod": "DW", "nazwa": "Wrocław", "typ": "miasto", "woj": "dolnośląskie", "lat": 51.1265, "lng": 16.9781, "wiki": "Wrocław"},
  {"kod": "DBL", "nazwa": "powiat bolesławiecki", "typ": "ziemski", "woj": "dolnośląskie", "lat": 51.3217, "lng": 15.521, "wiki": "Powiat_bolesławiecki", "siedziba": "Bolesławiec"},
  {"kod": "DDZ", "nazwa": "powiat dzierżoniowski", "typ": "ziemski", "woj": "dolnośląskie", "lat": 50.7352, "lng": 16.7058, "wiki": "Powiat_dzierżoniowski", "siedziba": "Dzierżoniów"},
  {"kod": "DGR", "nazwa": "powiat górowski", "typ": "ziemski", "woj": "dolnośląskie", "lat": 51.6367, "lng": 16.5563, "wiki": "Powiat_górowski", "siedziba": "Góra"},
  {"kod": "DGL", "nazwa": "powiat głogowski", "typ": "ziemski", "woj": "dolnośląskie", "lat": 51.6714, "lng": 16.0893, "wiki": "Powiat_głogowski", "siedziba": "Głogów"},
  {"kod": "DJA", "nazwa": "powiat jaworski", "typ": "ziemski", "woj": "dolnośląskie", "lat": 51.0011, "lng": 16.092, "wiki": "Powiat_jaworski", "siedziba": "Jawor"},
  {"kod": "DJE", "nazwa": "powiat jeleniogórski (karkonoski)", "typ": "ziemski", "woj": "dolnośląskie", "lat": 50.8745, "lng": 15.5556, "wiki": "Powiat_karkonoski", "siedziba": "Jelenia Góra"},
  {"kod": "DKA", "nazwa": "powiat kamiennogórski", "typ": "ziemski", "woj": "dolnośląskie", "lat": 50.7561, "lng": 15.9856, "wiki": "Powiat_kamiennogórski", "siedziba": "Kamienna Góra"},
  {"kod": "DKL", "nazwa": "powiat kłodzki", "typ": "ziemski", "woj": "dolnośląskie", "lat": 50.3888, "lng": 16.5887, "wiki": "Powiat_kłodzki", "siedziba": "Kłodzko"},
  {"kod": "DLE", "nazwa": "powiat legnicki", "typ": "ziemski", "woj": "dolnośląskie", "lat": 51.2413, "lng": 16.3438, "wiki": "Powiat_legnicki", "siedziba": "Legnica"},
  {"kod": "DLB", "nazwa": "powiat lubański", "typ": "ziemski", "woj": "dolnośląskie", "lat": 51.0451, "lng": 15.2759, "wiki": "Powiat_lubański", "siedziba": "Lubań"},
  {"kod": "DLU", "nazwa": "powiat lubiński", "typ": "ziemski", "woj": "dolnośląskie", "lat": 51.4417, "lng": 16.2576, "wiki": "Powiat_lubiński", "siedziba": "Lubin"},
  {"kod": "DLW", "nazwa": "powiat lwówecki", "typ": "ziemski", "woj": "dolnośląskie", "lat": 51.0157, "lng": 15.5592, "wiki": "Powiat_lwówecki", "siedziba": "Lwówek Śląski"},
  {"kod": "DMI", "nazwa": "powiat milicki", "typ": "ziemski", "woj": "dolnośląskie", "lat": 51.5081, "lng": 17.2969, "wiki": "Powiat_milicki", "siedziba": "Milicz"},
  {"kod": "DOL", "nazwa": "powiat oleśnicki", "typ": "ziemski", "woj": "dolnośląskie", "lat": 51.2546, "lng": 17.5008, "wiki": "Powiat_oleśnicki", "siedziba": "Oleśnica"},
  {"kod": "DOA", "nazwa": "powiat oławski", "typ": "ziemski", "woj": "dolnośląskie", "lat": 50.9605, "lng": 17.2852, "wiki": "Powiat_oławski", "siedziba": "Oława"},
  {"kod": "DPL", "nazwa": "powiat polkowicki", "typ": "ziemski", "woj": "dolnośląskie", "lat": 51.5004, "lng": 15.9942, "wiki": "Powiat_polkowicki", "siedziba": "Polkowice"},
  {"kod": "DSR", "nazwa": "powiat średzki", "typ": "ziemski", "woj": "dolnośląskie", "lat": 51.1261, "lng": 16.6301, "wiki": "Powiat_średzki", "siedziba": "Środa Śląska"},
  {"kod": "DST", "nazwa": "powiat strzeliński", "typ": "ziemski", "woj": "dolnośląskie", "lat": 50.7668, "lng": 17.0766, "wiki": "Powiat_strzeliński", "siedziba": "Strzelin"},
  {"kod": "DSW", "nazwa": "powiat świdnicki", "typ": "ziemski", "woj": "dolnośląskie", "lat": 50.8704, "lng": 16.4776, "wiki": "Powiat_świdnicki", "siedziba": "Świdnica"},
  {"kod": "DTR", "nazwa": "powiat trzebnicki", "typ": "ziemski", "woj": "dolnośląskie", "lat": 51.3719, "lng": 17.05, "wiki": "Powiat_trzebnicki", "siedziba": "Trzebnica"},
  {"kod": "DBA", "nazwa": "powiat wałbrzyski", "typ": "ziemski", "woj": "dolnośląskie", "lat": 50.7574, "lng": 16.1684, "wiki": "Powiat_wałbrzyski", "siedziba": "Wałbrzych"},
  {"kod": "DWL", "nazwa": "powiat wołowski", "typ": "ziemski", "woj": "dolnośląskie", "lat": 51.3721, "lng": 16.6271, "wiki": "Powiat_wołowski", "siedziba": "Wołów"},
  {"kod": "DWR", "nazwa": "powiat wrocławski", "typ": "ziemski", "woj": "dolnośląskie", "lat": 51.0431, "lng": 16.8731, "wiki": "Powiat_wrocławski", "siedziba": "Wrocław"},
  {"kod": "DZA", "nazwa": "powiat ząbkowicki", "typ": "ziemski", "woj": "dolnośląskie", "lat": 50.5568, "lng": 16.8564, "wiki": "Powiat_ząbkowicki", "siedziba": "Ząbkowice Śląskie"},
  {"kod": "DZG", "nazwa": "powiat zgorzelecki", "typ": "ziemski", "woj": "dolnośląskie", "lat": 51.1629, "lng": 15.0765, "wiki": "Powiat_zgorzelecki", "siedziba": "Zgorzelec"},
  {"kod": "DZL", "nazwa": "powiat złotoryjski", "typ": "ziemski", "woj": "dolnośląskie", "lat": 51.0913, "lng": 15.878, "wiki": "Powiat_złotoryjski", "siedziba": "Złotoryja"},
  // ========== ŁÓDZKIE ==========
  {"kod": "EP", "nazwa": "Piotrków Trybunalski", "typ": "miasto", "woj": "łódzkie", "lat": 51.4129, "lng": 19.6887, "wiki": "Piotrków_Trybunalski"},
  {"kod": "ES", "nazwa": "Skierniewice", "typ": "miasto", "woj": "łódzkie", "lat": 51.958, "lng": 20.1448, "wiki": "Skierniewice"},
  {"kod": "EL", "nazwa": "Łódź", "typ": "miasto", "woj": "łódzkie", "lat": 51.773, "lng": 19.4784, "wiki": "Łódź"},
  {"kod": "EBE", "nazwa": "powiat bełchatowski", "typ": "ziemski", "woj": "łódzkie", "lat": 51.3691, "lng": 19.2763, "wiki": "Powiat_bełchatowski", "siedziba": "Bełchatów"},
  {"kod": "EBR", "nazwa": "powiat brzeziński", "typ": "ziemski", "woj": "łódzkie", "lat": 51.8408, "lng": 19.8191, "wiki": "Powiat_brzeziński", "siedziba": "Brzeziny"},
  {"kod": "EKU", "nazwa": "powiat kutnowski", "typ": "ziemski", "woj": "łódzkie", "lat": 52.2515, "lng": 19.4269, "wiki": "Powiat_kutnowski", "siedziba": "Kutno"},
  {"kod": "EOP", "nazwa": "powiat opoczyński", "typ": "ziemski", "woj": "łódzkie", "lat": 51.3925, "lng": 20.1505, "wiki": "Powiat_opoczyński", "siedziba": "Opoczno"},
  {"kod": "EPA", "nazwa": "powiat pabianicki", "typ": "ziemski", "woj": "łódzkie", "lat": 51.6775, "lng": 19.321, "wiki": "Powiat_pabianicki", "siedziba": "Pabianice"},
  {"kod": "EPJ", "nazwa": "powiat pajęczański", "typ": "ziemski", "woj": "łódzkie", "lat": 51.1412, "lng": 19.0184, "wiki": "Powiat_pajęczański", "siedziba": "Pajęczno"},
  {"kod": "EPI", "nazwa": "powiat piotrkowski", "typ": "ziemski", "woj": "łódzkie", "lat": 51.3783, "lng": 19.5774, "wiki": "Powiat_piotrkowski", "siedziba": "Piotrków Trybunalski"},
  {"kod": "EPD", "nazwa": "powiat poddębicki", "typ": "ziemski", "woj": "łódzkie", "lat": 51.8984, "lng": 18.9642, "wiki": "Powiat_poddębicki", "siedziba": "Poddębice"},
  {"kod": "ERA", "nazwa": "powiat radomszczański", "typ": "ziemski", "woj": "łódzkie", "lat": 51.0648, "lng": 19.6311, "wiki": "Powiat_radomszczański", "siedziba": "Radomsko"},
  {"kod": "ERW", "nazwa": "powiat rawski", "typ": "ziemski", "woj": "łódzkie", "lat": 51.7623, "lng": 20.3768, "wiki": "Powiat_rawski", "siedziba": "Rawa Mazowiecka"},
  {"kod": "ESI", "nazwa": "powiat sieradzki", "typ": "ziemski", "woj": "łódzkie", "lat": 51.6034, "lng": 18.6133, "wiki": "Powiat_sieradzki", "siedziba": "Sieradz"},
  {"kod": "ESK", "nazwa": "powiat skierniewicki", "typ": "ziemski", "woj": "łódzkie", "lat": 51.9449, "lng": 20.0096, "wiki": "Powiat_skierniewicki", "siedziba": "Skierniewice"},
  {"kod": "ETM", "nazwa": "powiat tomaszowski", "typ": "ziemski", "woj": "łódzkie", "lat": 51.5968, "lng": 20.0674, "wiki": "Powiat_tomaszowski", "siedziba": "Tomaszów Mazowiecki"},
  {"kod": "EWI", "nazwa": "powiat wieluński", "typ": "ziemski", "woj": "łódzkie", "lat": 51.2327, "lng": 18.5818, "wiki": "Powiat_wieluński", "siedziba": "Wieluń"},
  {"kod": "EWE", "nazwa": "powiat wieruszowski", "typ": "ziemski", "woj": "łódzkie", "lat": 51.2942, "lng": 18.2567, "wiki": "Powiat_wieruszowski", "siedziba": "Wieruszów"},
  {"kod": "EZD", "nazwa": "powiat zduńskowolski", "typ": "ziemski", "woj": "łódzkie", "lat": 51.6204, "lng": 18.9474, "wiki": "Powiat_zduńskowolski", "siedziba": "Zduńska Wola"},
  {"kod": "EZG", "nazwa": "powiat zgierski", "typ": "ziemski", "woj": "łódzkie", "lat": 51.9042, "lng": 19.4395, "wiki": "Powiat_zgierski", "siedziba": "Zgierz"},
  {"kod": "ELA", "nazwa": "powiat łaski", "typ": "ziemski", "woj": "łódzkie", "lat": 51.5589, "lng": 19.1367, "wiki": "Powiat_łaski", "siedziba": "Łask"},
  {"kod": "ELE", "nazwa": "powiat łęczycki", "typ": "ziemski", "woj": "łódzkie", "lat": 52.106, "lng": 19.2359, "wiki": "Powiat_łęczycki", "siedziba": "Łęczyca"},
  {"kod": "ELW", "nazwa": "powiat łódzki wschodni", "typ": "ziemski", "woj": "łódzkie", "lat": 51.6862, "lng": 19.5884, "wiki": "Powiat_łódzki_wschodni", "siedziba": "Łódź"},
  {"kod": "ELC", "nazwa": "powiat łowicki", "typ": "ziemski", "woj": "łódzkie", "lat": 52.1105, "lng": 19.8245, "wiki": "Powiat_łowicki", "siedziba": "Łowicz"},
  // ========== LUBUSKIE ==========
  {"kod": "FG", "nazwa": "Gorzów Wielkopolski", "typ": "miasto", "woj": "lubuskie", "lat": 52.7306, "lng": 15.2107, "wiki": "Gorzów_Wielkopolski"},
  {"kod": "FZ", "nazwa": "Zielona Góra", "typ": "miasto", "woj": "lubuskie", "lat": 51.9277, "lng": 15.549, "wiki": "Zielona_Góra"},
  {"kod": "FGW", "nazwa": "powiat gorzowski", "typ": "ziemski", "woj": "lubuskie", "lat": 52.7386, "lng": 14.9663, "wiki": "Powiat_gorzowski", "siedziba": "Gorzów Wielkopolski"},
  {"kod": "FKR", "nazwa": "powiat krośnieński", "typ": "ziemski", "woj": "lubuskie", "lat": 52.0101, "lng": 14.9934, "wiki": "Powiat_krośnieński", "siedziba": "Krosno Odrzańskie"},
  {"kod": "FMI", "nazwa": "powiat międzyrzecki", "typ": "ziemski", "woj": "lubuskie", "lat": 52.4988, "lng": 15.5805, "wiki": "Powiat_międzyrzecki", "siedziba": "Międzyrzecz"},
  {"kod": "FNW", "nazwa": "powiat nowosolski", "typ": "ziemski", "woj": "lubuskie", "lat": 51.8422, "lng": 15.7035, "wiki": "Powiat_nowosolski", "siedziba": "Nowa Sól"},
  {"kod": "FSD", "nazwa": "powiat strzelecko-drezdenecki", "typ": "ziemski", "woj": "lubuskie", "lat": 52.9122, "lng": 15.6482, "wiki": "Powiat_strzelecko-drezdenecki", "siedziba": "Strzelce Krajeńskie"},
  {"kod": "FSU", "nazwa": "powiat sulęciński", "typ": "ziemski", "woj": "lubuskie", "lat": 52.4279, "lng": 15.1802, "wiki": "Powiat_sulęciński", "siedziba": "Sulęcin"},
  {"kod": "FSW", "nazwa": "powiat świebodziński", "typ": "ziemski", "woj": "lubuskie", "lat": 52.2373, "lng": 15.5066, "wiki": "Powiat_świebodziński", "siedziba": "Świebodzin"},
  {"kod": "FSL", "nazwa": "powiat słubicki", "typ": "ziemski", "woj": "lubuskie", "lat": 52.3227, "lng": 14.739, "wiki": "Powiat_słubicki", "siedziba": "Słubice"},
  {"kod": "FWS", "nazwa": "powiat wschowski", "typ": "ziemski", "woj": "lubuskie", "lat": 51.8301, "lng": 16.1201, "wiki": "Powiat_wschowski", "siedziba": "Wschowa"},
  {"kod": "FZG", "nazwa": "powiat żagański", "typ": "ziemski", "woj": "lubuskie", "lat": 51.5951, "lng": 15.5281, "wiki": "Powiat_żagański", "siedziba": "Żagań"},
  {"kod": "FZA", "nazwa": "powiat żarski", "typ": "ziemski", "woj": "lubuskie", "lat": 51.6283, "lng": 15.0074, "wiki": "Powiat_żarski", "siedziba": "Żary"},
  {"kod": "FZI", "nazwa": "powiat zielonogórski", "typ": "ziemski", "woj": "lubuskie", "lat": 51.9758, "lng": 15.7634, "wiki": "Powiat_zielonogórski", "siedziba": "Zielona Góra"},
  // ========== POMORSKIE ==========
  {"kod": "GD", "nazwa": "Gdańsk", "typ": "miasto", "woj": "pomorskie", "lat": 54.3611, "lng": 18.6287, "wiki": "Gdańsk"},
  {"kod": "GA", "nazwa": "Gdynia", "typ": "miasto", "woj": "pomorskie", "lat": 54.5037, "lng": 18.4626, "wiki": "Gdynia"},
  {"kod": "GSP", "nazwa": "Sopot", "typ": "miasto", "woj": "pomorskie", "lat": 54.4418, "lng": 18.5433, "wiki": "Sopot"},
  {"kod": "GS", "nazwa": "Słupsk", "typ": "miasto", "woj": "pomorskie", "lat": 54.4607, "lng": 17.0277, "wiki": "Słupsk"},
  {"kod": "GBY", "nazwa": "powiat bytowski", "typ": "ziemski", "woj": "pomorskie", "lat": 54.1575, "lng": 17.3787, "wiki": "Powiat_bytowski", "siedziba": "Bytów"},
  {"kod": "GCH", "nazwa": "powiat chojnicki", "typ": "ziemski", "woj": "pomorskie", "lat": 53.801, "lng": 17.7278, "wiki": "Powiat_chojnicki", "siedziba": "Chojnice"},
  {"kod": "GCZ", "nazwa": "powiat człuchowski", "typ": "ziemski", "woj": "pomorskie", "lat": 53.7511, "lng": 17.1669, "wiki": "Powiat_człuchowski", "siedziba": "Człuchów"},
  {"kod": "GDA", "nazwa": "powiat gdański", "typ": "ziemski", "woj": "pomorskie", "lat": 54.2248, "lng": 18.5917, "wiki": "Powiat_gdański", "siedziba": "Gdańsk"},
  {"kod": "GKA", "nazwa": "powiat kartuski", "typ": "ziemski", "woj": "pomorskie", "lat": 54.3269, "lng": 18.1088, "wiki": "Powiat_kartuski", "siedziba": "Kartuzy"},
  {"kod": "GKS", "nazwa": "powiat kościerski", "typ": "ziemski", "woj": "pomorskie", "lat": 54.0194, "lng": 17.9714, "wiki": "Powiat_kościerski", "siedziba": "Kościerzyna"},
  {"kod": "GKW", "nazwa": "powiat kwidzyński", "typ": "ziemski", "woj": "pomorskie", "lat": 53.747, "lng": 19.0768, "wiki": "Powiat_kwidzyński", "siedziba": "Kwidzyn"},
  {"kod": "GLE", "nazwa": "powiat lęborski", "typ": "ziemski", "woj": "pomorskie", "lat": 54.5683, "lng": 17.6888, "wiki": "Powiat_lęborski", "siedziba": "Lębork"},
  {"kod": "GMB", "nazwa": "powiat malborski", "typ": "ziemski", "woj": "pomorskie", "lat": 54.0632, "lng": 19.028, "wiki": "Powiat_malborski", "siedziba": "Malbork"},
  {"kod": "GND", "nazwa": "powiat nowodworski", "typ": "ziemski", "woj": "pomorskie", "lat": 54.2875, "lng": 19.1031, "wiki": "Powiat_nowodworski", "siedziba": "Nowy Dwór Gdański"},
  {"kod": "GPU", "nazwa": "powiat pucki", "typ": "ziemski", "woj": "pomorskie", "lat": 54.697, "lng": 18.325, "wiki": "Powiat_pucki", "siedziba": "Puck"},
  {"kod": "GST", "nazwa": "powiat starogardzki", "typ": "ziemski", "woj": "pomorskie", "lat": 53.8991, "lng": 18.3716, "wiki": "Powiat_starogardzki", "siedziba": "Starogard Gdański"},
  {"kod": "GSZ", "nazwa": "powiat sztumski", "typ": "ziemski", "woj": "pomorskie", "lat": 53.9013, "lng": 19.2614, "wiki": "Powiat_sztumski", "siedziba": "Sztum"},
  {"kod": "GSL", "nazwa": "powiat słupski", "typ": "ziemski", "woj": "pomorskie", "lat": 54.4223, "lng": 17.1657, "wiki": "Powiat_słupski", "siedziba": "Słupsk"},
  {"kod": "GTC", "nazwa": "powiat tczewski", "typ": "ziemski", "woj": "pomorskie", "lat": 53.9189, "lng": 18.747, "wiki": "Powiat_tczewski", "siedziba": "Tczew"},
  {"kod": "GWE", "nazwa": "powiat wejherowski", "typ": "ziemski", "woj": "pomorskie", "lat": 54.6166, "lng": 18.1023, "wiki": "Powiat_wejherowski", "alt": ["GWO"], "siedziba": "Wejherowo"},
  // ========== MAŁOPOLSKIE ==========
  {"kod": "KR", "nazwa": "Kraków", "typ": "miasto", "woj": "małopolskie", "lat": 50.0469, "lng": 19.9972, "wiki": "Kraków", "alt": ["KK"]},
  {"kod": "KN", "nazwa": "Nowy Sącz", "typ": "miasto", "woj": "małopolskie", "lat": 49.6103, "lng": 20.7164, "wiki": "Nowy_Sącz"},
  {"kod": "KT", "nazwa": "Tarnów", "typ": "miasto", "woj": "małopolskie", "lat": 50.026, "lng": 20.964, "wiki": "Tarnów"},
  {"kod": "KBC", "nazwa": "powiat bocheński", "typ": "ziemski", "woj": "małopolskie", "lat": 49.9605, "lng": 20.4317, "wiki": "Powiat_bocheński", "alt": ["KBA"], "siedziba": "Bochnia"},
  {"kod": "KBR", "nazwa": "powiat brzeski", "typ": "ziemski", "woj": "małopolskie", "lat": 49.9813, "lng": 20.659, "wiki": "Powiat_brzeski", "siedziba": "Brzesko"},
  {"kod": "KCH", "nazwa": "powiat chrzanowski", "typ": "ziemski", "woj": "małopolskie", "lat": 50.1206, "lng": 19.4082, "wiki": "Powiat_chrzanowski", "siedziba": "Chrzanów"},
  {"kod": "KDA", "nazwa": "powiat dąbrowski", "typ": "ziemski", "woj": "małopolskie", "lat": 50.2309, "lng": 20.9462, "wiki": "Powiat_dąbrowski", "siedziba": "Dąbrowa Tarnowska"},
  {"kod": "KGR", "nazwa": "powiat gorlicki", "typ": "ziemski", "woj": "małopolskie", "lat": 49.5913, "lng": 21.1668, "wiki": "Powiat_gorlicki", "siedziba": "Gorlice"},
  {"kod": "KRA", "nazwa": "powiat krakowski", "typ": "ziemski", "woj": "małopolskie", "lat": 50.0999, "lng": 19.7077, "wiki": "Powiat_krakowski", "siedziba": "Kraków"},
  {"kod": "KLI", "nazwa": "powiat limanowski", "typ": "ziemski", "woj": "małopolskie", "lat": 49.6826, "lng": 20.296, "wiki": "Powiat_limanowski", "siedziba": "Limanowa"},
  {"kod": "KMI", "nazwa": "powiat miechowski", "typ": "ziemski", "woj": "małopolskie", "lat": 50.3897, "lng": 20.0778, "wiki": "Powiat_miechowski", "siedziba": "Miechów"},
  {"kod": "KMY", "nazwa": "powiat myślenicki", "typ": "ziemski", "woj": "małopolskie", "lat": 49.7751, "lng": 19.9761, "wiki": "Powiat_myślenicki", "siedziba": "Myślenice"},
  {"kod": "KNS", "nazwa": "powiat nowosądecki", "typ": "ziemski", "woj": "małopolskie", "lat": 49.5515, "lng": 20.6967, "wiki": "Powiat_nowosądecki", "siedziba": "Nowy Sącz"},
  {"kod": "KNT", "nazwa": "powiat nowotarski", "typ": "ziemski", "woj": "małopolskie", "lat": 49.4934, "lng": 19.9992, "wiki": "Powiat_nowotarski", "siedziba": "Nowy Targ"},
  {"kod": "KOL", "nazwa": "powiat olkuski", "typ": "ziemski", "woj": "małopolskie", "lat": 50.3194, "lng": 19.6492, "wiki": "Powiat_olkuski", "siedziba": "Olkusz"},
  {"kod": "KOS", "nazwa": "powiat oświęcimski", "typ": "ziemski", "woj": "małopolskie", "lat": 49.9923, "lng": 19.2968, "wiki": "Powiat_oświęcimski", "siedziba": "Oświęcim"},
  {"kod": "KPR", "nazwa": "powiat proszowicki", "typ": "ziemski", "woj": "małopolskie", "lat": 50.217, "lng": 20.2665, "wiki": "Powiat_proszowicki", "siedziba": "Proszowice"},
  {"kod": "KSU", "nazwa": "powiat suski", "typ": "ziemski", "woj": "małopolskie", "lat": 49.7017, "lng": 19.6483, "wiki": "Powiat_suski", "siedziba": "Sucha Beskidzka"},
  {"kod": "KTA", "nazwa": "powiat tarnowski", "typ": "ziemski", "woj": "małopolskie", "lat": 49.9856, "lng": 21.0381, "wiki": "Powiat_tarnowski", "siedziba": "Tarnów"},
  {"kod": "KTT", "nazwa": "powiat tatrzański", "typ": "ziemski", "woj": "małopolskie", "lat": 49.3035, "lng": 19.9644, "wiki": "Powiat_tatrzański", "siedziba": "Zakopane"},
  {"kod": "KWA", "nazwa": "powiat wadowicki", "typ": "ziemski", "woj": "małopolskie", "lat": 49.8945, "lng": 19.5347, "wiki": "Powiat_wadowicki", "siedziba": "Wadowice"},
  {"kod": "KWI", "nazwa": "powiat wielicki", "typ": "ziemski", "woj": "małopolskie", "lat": 49.9819, "lng": 20.1729, "wiki": "Powiat_wielicki", "siedziba": "Wieliczka"},
  // ========== LUBELSKIE ==========
  {"kod": "LB", "nazwa": "Biała Podlaska", "typ": "miasto", "woj": "lubelskie", "lat": 52.0293, "lng": 23.1495, "wiki": "Biała_Podlaska"},
  {"kod": "LC", "nazwa": "Chełm", "typ": "miasto", "woj": "lubelskie", "lat": 51.1358, "lng": 23.4937, "wiki": "Chełm"},
  {"kod": "LU", "nazwa": "Lublin", "typ": "miasto", "woj": "lubelskie", "lat": 51.2182, "lng": 22.5547, "wiki": "Lublin"},
  {"kod": "LZ", "nazwa": "Zamość", "typ": "miasto", "woj": "lubelskie", "lat": 50.7215, "lng": 23.2597, "wiki": "Zamość"},
  {"kod": "LBI", "nazwa": "powiat bialski", "typ": "ziemski", "woj": "lubelskie", "lat": 51.9719, "lng": 23.1499, "wiki": "Powiat_bialski", "siedziba": "Biała Podlaska"},
  {"kod": "LBL", "nazwa": "powiat biłgorajski", "typ": "ziemski", "woj": "lubelskie", "lat": 50.5857, "lng": 22.7489, "wiki": "Powiat_biłgorajski", "siedziba": "Biłgoraj"},
  {"kod": "LCH", "nazwa": "powiat chełmski", "typ": "ziemski", "woj": "lubelskie", "lat": 51.1219, "lng": 23.2557, "wiki": "Powiat_chełmski", "siedziba": "Chełm"},
  {"kod": "LHR", "nazwa": "powiat hrubieszowski", "typ": "ziemski", "woj": "lubelskie", "lat": 50.7078, "lng": 23.849, "wiki": "Powiat_hrubieszowski", "siedziba": "Hrubieszów"},
  {"kod": "LJA", "nazwa": "powiat janowski", "typ": "ziemski", "woj": "lubelskie", "lat": 50.7454, "lng": 22.4234, "wiki": "Powiat_janowski", "siedziba": "Janów Lubelski"},
  {"kod": "LKR", "nazwa": "powiat kraśnicki", "typ": "ziemski", "woj": "lubelskie", "lat": 50.9155, "lng": 22.1403, "wiki": "Powiat_kraśnicki", "siedziba": "Kraśnik"},
  {"kod": "LKS", "nazwa": "powiat krasnostawski", "typ": "ziemski", "woj": "lubelskie", "lat": 50.9635, "lng": 23.0995, "wiki": "Powiat_krasnostawski", "siedziba": "Krasnystaw"},
  {"kod": "LLB", "nazwa": "powiat lubartowski", "typ": "ziemski", "woj": "lubelskie", "lat": 51.535, "lng": 22.5165, "wiki": "Powiat_lubartowski", "siedziba": "Lubartów"},
  {"kod": "LUB", "nazwa": "powiat lubelski", "typ": "ziemski", "woj": "lubelskie", "lat": 51.1343, "lng": 22.4383, "wiki": "Powiat_lubelski", "siedziba": "Lublin"},
  {"kod": "LOP", "nazwa": "powiat opolski", "typ": "ziemski", "woj": "lubelskie", "lat": 51.129, "lng": 22.0009, "wiki": "Powiat_opolski", "siedziba": "Opole Lubelskie"},
  {"kod": "LPA", "nazwa": "powiat parczewski", "typ": "ziemski", "woj": "lubelskie", "lat": 51.6001, "lng": 22.9324, "wiki": "Powiat_parczewski", "siedziba": "Parczew"},
  {"kod": "LPU", "nazwa": "powiat puławski", "typ": "ziemski", "woj": "lubelskie", "lat": 51.4184, "lng": 22.0702, "wiki": "Powiat_puławski", "siedziba": "Puławy"},
  {"kod": "LRA", "nazwa": "powiat radzyński", "typ": "ziemski", "woj": "lubelskie", "lat": 51.7826, "lng": 22.6697, "wiki": "Powiat_radzyński", "siedziba": "Radzyń Podlaski"},
  {"kod": "LRY", "nazwa": "powiat rycki", "typ": "ziemski", "woj": "lubelskie", "lat": 51.6621, "lng": 22.0064, "wiki": "Powiat_rycki", "siedziba": "Ryki"},
  {"kod": "LSW", "nazwa": "powiat świdnicki", "typ": "ziemski", "woj": "lubelskie", "lat": 51.1246, "lng": 22.8815, "wiki": "Powiat_świdnicki", "siedziba": "Świdnik"},
  {"kod": "LTM", "nazwa": "powiat tomaszowski", "typ": "ziemski", "woj": "lubelskie", "lat": 50.4781, "lng": 23.5796, "wiki": "Powiat_tomaszowski", "siedziba": "Tomaszów Lubelski"},
  {"kod": "LWL", "nazwa": "powiat włodawski", "typ": "ziemski", "woj": "lubelskie", "lat": 51.523, "lng": 23.4079, "wiki": "Powiat_włodawski", "siedziba": "Włodawa"},
  {"kod": "LZA", "nazwa": "powiat zamojski", "typ": "ziemski", "woj": "lubelskie", "lat": 50.6919, "lng": 23.2071, "wiki": "Powiat_zamojski", "siedziba": "Zamość"},
  {"kod": "LLE", "nazwa": "powiat łęczyński", "typ": "ziemski", "woj": "lubelskie", "lat": 51.3046, "lng": 22.9958, "wiki": "Powiat_łęczyński", "siedziba": "Łęczna"},
  {"kod": "LLU", "nazwa": "powiat łukowski", "typ": "ziemski", "woj": "lubelskie", "lat": 51.8537, "lng": 22.1165, "wiki": "Powiat_łukowski", "siedziba": "Łuków"},
  // ========== WARMIŃSKO-MAZURSKIE ==========
  {"kod": "NE", "nazwa": "Elbląg", "typ": "miasto", "woj": "warmińsko-mazurskie", "lat": 54.1986, "lng": 19.4411, "wiki": "Elbląg"},
  {"kod": "NO", "nazwa": "Olsztyn", "typ": "miasto", "woj": "warmińsko-mazurskie", "lat": 53.7764, "lng": 20.4777, "wiki": "Olsztyn"},
  {"kod": "NBA", "nazwa": "powiat bartoszycki", "typ": "ziemski", "woj": "warmińsko-mazurskie", "lat": 54.2126, "lng": 20.5685, "wiki": "Powiat_bartoszycki", "siedziba": "Bartoszyce"},
  {"kod": "NBR", "nazwa": "powiat braniewski", "typ": "ziemski", "woj": "warmińsko-mazurskie", "lat": 54.2777, "lng": 19.9556, "wiki": "Powiat_braniewski", "siedziba": "Braniewo"},
  {"kod": "NDZ", "nazwa": "powiat działdowski", "typ": "ziemski", "woj": "warmińsko-mazurskie", "lat": 53.2888, "lng": 19.9816, "wiki": "Powiat_działdowski", "siedziba": "Działdowo"},
  {"kod": "NEB", "nazwa": "powiat elbląski", "typ": "ziemski", "woj": "warmińsko-mazurskie", "lat": 54.1593, "lng": 19.6383, "wiki": "Powiat_elbląski", "siedziba": "Elbląg"},
  {"kod": "NEL", "nazwa": "powiat ełcki", "typ": "ziemski", "woj": "warmińsko-mazurskie", "lat": 53.8167, "lng": 22.4321, "wiki": "Powiat_ełcki", "siedziba": "Ełk"},
  {"kod": "NGI", "nazwa": "powiat giżycki", "typ": "ziemski", "woj": "warmińsko-mazurskie", "lat": 54.0181, "lng": 21.8534, "wiki": "Powiat_giżycki", "siedziba": "Giżycko"},
  {"kod": "NGO", "nazwa": "powiat gołdapski", "typ": "ziemski", "woj": "warmińsko-mazurskie", "lat": 54.2606, "lng": 22.2813, "wiki": "Powiat_gołdapski", "siedziba": "Gołdap"},
  {"kod": "NIL", "nazwa": "powiat iławski", "typ": "ziemski", "woj": "warmińsko-mazurskie", "lat": 53.6748, "lng": 19.4915, "wiki": "Powiat_iławski", "siedziba": "Iława"},
  {"kod": "NKE", "nazwa": "powiat kętrzyński", "typ": "ziemski", "woj": "warmińsko-mazurskie", "lat": 54.1362, "lng": 21.2893, "wiki": "Powiat_kętrzyński", "siedziba": "Kętrzyn"},
  {"kod": "NLI", "nazwa": "powiat lidzbarski", "typ": "ziemski", "woj": "warmińsko-mazurskie", "lat": 54.1058, "lng": 20.4275, "wiki": "Powiat_lidzbarski", "siedziba": "Lidzbark Warmiński"},
  {"kod": "NMR", "nazwa": "powiat mrągowski", "typ": "ziemski", "woj": "warmińsko-mazurskie", "lat": 53.8109, "lng": 21.4024, "wiki": "Powiat_mrągowski", "siedziba": "Mrągowo"},
  {"kod": "NNI", "nazwa": "powiat nidzicki", "typ": "ziemski", "woj": "warmińsko-mazurskie", "lat": 53.3725, "lng": 20.4888, "wiki": "Powiat_nidzicki", "siedziba": "Nidzica"},
  {"kod": "NNM", "nazwa": "powiat nowomiejski", "typ": "ziemski", "woj": "warmińsko-mazurskie", "lat": 53.4357, "lng": 19.5493, "wiki": "Powiat_nowomiejski", "siedziba": "Nowe Miasto Lubawskie"},
  {"kod": "NOE", "nazwa": "powiat olecki", "typ": "ziemski", "woj": "warmińsko-mazurskie", "lat": 54.0515, "lng": 22.4081, "wiki": "Powiat_olecki", "siedziba": "Olecko"},
  {"kod": "NOL", "nazwa": "powiat olsztyński", "typ": "ziemski", "woj": "warmińsko-mazurskie", "lat": 53.7788, "lng": 20.733, "wiki": "Powiat_olsztyński", "siedziba": "Olsztyn"},
  {"kod": "NOS", "nazwa": "powiat ostródzki", "typ": "ziemski", "woj": "warmińsko-mazurskie", "lat": 53.7292, "lng": 19.9342, "wiki": "Powiat_ostródzki", "siedziba": "Ostróda"},
  {"kod": "NPI", "nazwa": "powiat piski", "typ": "ziemski", "woj": "warmińsko-mazurskie", "lat": 53.6808, "lng": 21.8222, "wiki": "Powiat_piski", "siedziba": "Pisz"},
  {"kod": "NSZ", "nazwa": "powiat szczycieński", "typ": "ziemski", "woj": "warmińsko-mazurskie", "lat": 53.5417, "lng": 21.0184, "wiki": "Powiat_szczycieński", "siedziba": "Szczytno"},
  {"kod": "NWE", "nazwa": "powiat węgorzewski", "typ": "ziemski", "woj": "warmińsko-mazurskie", "lat": 54.2074, "lng": 21.7918, "wiki": "Powiat_węgorzewski", "siedziba": "Węgorzewo"},
  // ========== OPOLSKIE ==========
  {"kod": "OP", "nazwa": "Opole", "typ": "miasto", "woj": "opolskie", "lat": 50.6788, "lng": 17.9298, "wiki": "Opole"},
  {"kod": "OB", "nazwa": "powiat brzeski", "typ": "ziemski", "woj": "opolskie", "lat": 50.7894, "lng": 17.5356, "wiki": "Powiat_brzeski", "siedziba": "Brzeg"},
  {"kod": "OGL", "nazwa": "powiat głubczycki", "typ": "ziemski", "woj": "opolskie", "lat": 50.1484, "lng": 17.8325, "wiki": "Powiat_głubczycki", "siedziba": "Głubczyce"},
  {"kod": "OK", "nazwa": "powiat kędzierzyńsko-kozielski", "typ": "ziemski", "woj": "opolskie", "lat": 50.2938, "lng": 18.1613, "wiki": "Powiat_kędzierzyńsko-kozielski", "siedziba": "Kędzierzyn-Koźle"},
  {"kod": "OKL", "nazwa": "powiat kluczborski", "typ": "ziemski", "woj": "opolskie", "lat": 50.9856, "lng": 18.1458, "wiki": "Powiat_kluczborski", "siedziba": "Kluczbork"},
  {"kod": "OKR", "nazwa": "powiat krapkowicki", "typ": "ziemski", "woj": "opolskie", "lat": 50.453, "lng": 17.9552, "wiki": "Powiat_krapkowicki", "siedziba": "Krapkowice"},
  {"kod": "ONA", "nazwa": "powiat namysłowski", "typ": "ziemski", "woj": "opolskie", "lat": 51.016, "lng": 17.7224, "wiki": "Powiat_namysłowski", "siedziba": "Namysłów"},
  {"kod": "ONY", "nazwa": "powiat nyski", "typ": "ziemski", "woj": "opolskie", "lat": 50.4605, "lng": 17.3044, "wiki": "Powiat_nyski", "siedziba": "Nysa"},
  {"kod": "OOL", "nazwa": "powiat oleski", "typ": "ziemski", "woj": "opolskie", "lat": 50.8788, "lng": 18.4831, "wiki": "Powiat_oleski", "siedziba": "Olesno"},
  {"kod": "OPO", "nazwa": "powiat opolski", "typ": "ziemski", "woj": "opolskie", "lat": 50.735, "lng": 18.0871, "wiki": "Powiat_opolski", "siedziba": "Opole"},
  {"kod": "OPR", "nazwa": "powiat prudnicki", "typ": "ziemski", "woj": "opolskie", "lat": 50.4098, "lng": 17.6634, "wiki": "Powiat_prudnicki", "siedziba": "Prudnik"},
  {"kod": "OST", "nazwa": "powiat strzelecki", "typ": "ziemski", "woj": "opolskie", "lat": 50.5306, "lng": 18.2684, "wiki": "Powiat_strzelecki", "siedziba": "Strzelce Opolskie"},
  // ========== WIELKOPOLSKIE ==========
  {"kod": "PK", "nazwa": "Kalisz", "typ": "miasto", "woj": "wielkopolskie", "lat": 51.7473, "lng": 18.0796, "wiki": "Kalisz"},
  {"kod": "PN", "nazwa": "Konin", "typ": "miasto", "woj": "wielkopolskie", "lat": 52.2561, "lng": 18.2683, "wiki": "Konin"},
  {"kod": "PL", "nazwa": "Leszno", "typ": "miasto", "woj": "wielkopolskie", "lat": 51.844, "lng": 16.5801, "wiki": "Leszno"},
  {"kod": "PO", "nazwa": "Poznań", "typ": "miasto", "woj": "wielkopolskie", "lat": 52.4006, "lng": 16.9198, "wiki": "Poznań", "alt": ["PY"]},
  {"kod": "PCH", "nazwa": "powiat chodzieski", "typ": "ziemski", "woj": "wielkopolskie", "lat": 52.9526, "lng": 16.9691, "wiki": "Powiat_chodzieski", "siedziba": "Chodzież"},
  {"kod": "PCT", "nazwa": "powiat czarnkowsko-trzcianecki", "typ": "ziemski", "woj": "wielkopolskie", "lat": 52.9288, "lng": 16.373, "wiki": "Powiat_czarnkowsko-trzcianecki", "siedziba": "Czarnków"},
  {"kod": "PGN", "nazwa": "powiat gnieźnieński", "typ": "ziemski", "woj": "wielkopolskie", "lat": 52.5536, "lng": 17.5868, "wiki": "Powiat_gnieźnieński", "siedziba": "Gniezno"},
  {"kod": "PGS", "nazwa": "powiat gostyński", "typ": "ziemski", "woj": "wielkopolskie", "lat": 51.8368, "lng": 17.0966, "wiki": "Powiat_gostyński", "siedziba": "Gostyń"},
  {"kod": "PGO", "nazwa": "powiat grodziski", "typ": "ziemski", "woj": "wielkopolskie", "lat": 52.1603, "lng": 16.3768, "wiki": "Powiat_grodziski", "siedziba": "Grodzisk Wielkopolski"},
  {"kod": "PJA", "nazwa": "powiat jarociński", "typ": "ziemski", "woj": "wielkopolskie", "lat": 52.0095, "lng": 17.5136, "wiki": "Powiat_jarociński", "siedziba": "Jarocin"},
  {"kod": "PKA", "nazwa": "powiat kaliski", "typ": "ziemski", "woj": "wielkopolskie", "lat": 51.7891, "lng": 18.2548, "wiki": "Powiat_kaliski", "siedziba": "Kalisz"},
  {"kod": "PKE", "nazwa": "powiat kępiński", "typ": "ziemski", "woj": "wielkopolskie", "lat": 51.2486, "lng": 17.9566, "wiki": "Powiat_kępiński", "siedziba": "Kępno"},
  {"kod": "PKL", "nazwa": "powiat kolski", "typ": "ziemski", "woj": "wielkopolskie", "lat": 52.2445, "lng": 18.8181, "wiki": "Powiat_kolski", "siedziba": "Koło"},
  {"kod": "PKN", "nazwa": "powiat koniński", "typ": "ziemski", "woj": "wielkopolskie", "lat": 52.2595, "lng": 18.4081, "wiki": "Powiat_koniński", "siedziba": "Konin"},
  {"kod": "PKS", "nazwa": "powiat kościański", "typ": "ziemski", "woj": "wielkopolskie", "lat": 52.0662, "lng": 16.6688, "wiki": "Powiat_kościański", "siedziba": "Kościan"},
  {"kod": "PKR", "nazwa": "powiat krotoszyński", "typ": "ziemski", "woj": "wielkopolskie", "lat": 51.7416, "lng": 17.4309, "wiki": "Powiat_krotoszyński", "siedziba": "Krotoszyn"},
  {"kod": "PLE", "nazwa": "powiat leszczyński", "typ": "ziemski", "woj": "wielkopolskie", "lat": 51.85, "lng": 16.7376, "wiki": "Powiat_leszczyński", "siedziba": "Leszno"},
  {"kod": "PMI", "nazwa": "powiat międzychodzki", "typ": "ziemski", "woj": "wielkopolskie", "lat": 52.6018, "lng": 16.0335, "wiki": "Powiat_międzychodzki", "siedziba": "Międzychód"},
  {"kod": "PNT", "nazwa": "powiat nowotomyski", "typ": "ziemski", "woj": "wielkopolskie", "lat": 52.3483, "lng": 16.1785, "wiki": "Powiat_nowotomyski", "siedziba": "Nowy Tomyśl"},
  {"kod": "POB", "nazwa": "powiat obornicki", "typ": "ziemski", "woj": "wielkopolskie", "lat": 52.7167, "lng": 16.846, "wiki": "Powiat_obornicki", "siedziba": "Oborniki"},
  {"kod": "POS", "nazwa": "powiat ostrowski", "typ": "ziemski", "woj": "wielkopolskie", "lat": 51.608, "lng": 17.8377, "wiki": "Powiat_ostrowski", "siedziba": "Ostrów Wielkopolski"},
  {"kod": "POT", "nazwa": "powiat ostrzeszowski", "typ": "ziemski", "woj": "wielkopolskie", "lat": 51.4378, "lng": 17.9749, "wiki": "Powiat_ostrzeszowski", "siedziba": "Ostrzeszów"},
  {"kod": "PP", "nazwa": "powiat pilski", "typ": "ziemski", "woj": "wielkopolskie", "lat": 53.1578, "lng": 16.893, "wiki": "Powiat_pilski", "siedziba": "Piła"},
  {"kod": "PPL", "nazwa": "powiat pleszewski", "typ": "ziemski", "woj": "wielkopolskie", "lat": 51.9254, "lng": 17.8239, "wiki": "Powiat_pleszewski", "siedziba": "Pleszew"},
  {"kod": "PZ", "nazwa": "powiat poznański", "typ": "ziemski", "woj": "wielkopolskie", "lat": 52.4162, "lng": 17.2153, "wiki": "Powiat_poznański", "siedziba": "Poznań"},
  {"kod": "PRA", "nazwa": "powiat rawicki", "typ": "ziemski", "woj": "wielkopolskie", "lat": 51.645, "lng": 16.9845, "wiki": "Powiat_rawicki", "siedziba": "Rawicz"},
  {"kod": "PSR", "nazwa": "powiat średzki", "typ": "ziemski", "woj": "wielkopolskie", "lat": 52.1802, "lng": 17.2618, "wiki": "Powiat_średzki", "siedziba": "Środa Wielkopolska"},
  {"kod": "PSE", "nazwa": "powiat śremski", "typ": "ziemski", "woj": "wielkopolskie", "lat": 52.0614, "lng": 17.101, "wiki": "Powiat_śremski", "siedziba": "Śrem"},
  {"kod": "PSZ", "nazwa": "powiat szamotulski", "typ": "ziemski", "woj": "wielkopolskie", "lat": 52.5841, "lng": 16.4785, "wiki": "Powiat_szamotulski", "siedziba": "Szamotuły"},
  {"kod": "PSL", "nazwa": "powiat słupecki", "typ": "ziemski", "woj": "wielkopolskie", "lat": 52.3143, "lng": 17.8881, "wiki": "Powiat_słupecki", "siedziba": "Słupca"},
  {"kod": "PTU", "nazwa": "powiat turecki", "typ": "ziemski", "woj": "wielkopolskie", "lat": 51.996, "lng": 18.4932, "wiki": "Powiat_turecki", "siedziba": "Turek"},
  {"kod": "PWA", "nazwa": "powiat wągrowiecki", "typ": "ziemski", "woj": "wielkopolskie", "lat": 52.8255, "lng": 17.2916, "wiki": "Powiat_wągrowiecki", "siedziba": "Wągrowiec"},
  {"kod": "PWL", "nazwa": "powiat wolsztyński", "typ": "ziemski", "woj": "wielkopolskie", "lat": 52.0879, "lng": 16.1002, "wiki": "Powiat_wolsztyński", "siedziba": "Wolsztyn"},
  {"kod": "PWR", "nazwa": "powiat wrzesiński", "typ": "ziemski", "woj": "wielkopolskie", "lat": 52.241, "lng": 17.6143, "wiki": "Powiat_wrzesiński", "siedziba": "Września"},
  {"kod": "PZL", "nazwa": "powiat złotowski", "typ": "ziemski", "woj": "wielkopolskie", "lat": 53.4125, "lng": 16.8781, "wiki": "Powiat_złotowski", "siedziba": "Złotów"},
  // ========== PODKARPACKIE ==========
  {"kod": "RK", "nazwa": "Krosno", "typ": "miasto", "woj": "podkarpackie", "lat": 49.6894, "lng": 21.7536, "wiki": "Krosno"},
  {"kod": "RP", "nazwa": "Przemyśl", "typ": "miasto", "woj": "podkarpackie", "lat": 49.7835, "lng": 22.7885, "wiki": "Przemyśl"},
  {"kod": "RZ", "nazwa": "Rzeszów", "typ": "miasto", "woj": "podkarpackie", "lat": 50.0071, "lng": 22.0099, "wiki": "Rzeszów"},
  {"kod": "RT", "nazwa": "Tarnobrzeg", "typ": "miasto", "woj": "podkarpackie", "lat": 50.5837, "lng": 21.7118, "wiki": "Tarnobrzeg"},
  {"kod": "RBI", "nazwa": "powiat bieszczadzki", "typ": "ziemski", "woj": "podkarpackie", "lat": 49.3364, "lng": 22.6305, "wiki": "Powiat_bieszczadzki", "siedziba": "Ustrzyki Dolne"},
  {"kod": "RBR", "nazwa": "powiat brzozowski", "typ": "ziemski", "woj": "podkarpackie", "lat": 49.7278, "lng": 22.0942, "wiki": "Powiat_brzozowski", "siedziba": "Brzozów"},
  {"kod": "RDE", "nazwa": "powiat dębicki", "typ": "ziemski", "woj": "podkarpackie", "lat": 49.9993, "lng": 21.3111, "wiki": "Powiat_dębicki", "siedziba": "Dębica"},
  {"kod": "RJA", "nazwa": "powiat jarosławski", "typ": "ziemski", "woj": "podkarpackie", "lat": 50.0251, "lng": 22.7994, "wiki": "Powiat_jarosławski", "siedziba": "Jarosław"},
  {"kod": "RJS", "nazwa": "powiat jasielski", "typ": "ziemski", "woj": "podkarpackie", "lat": 49.6427, "lng": 21.4657, "wiki": "Powiat_jasielski", "siedziba": "Jasło"},
  {"kod": "RKL", "nazwa": "powiat kolbuszowski", "typ": "ziemski", "woj": "podkarpackie", "lat": 50.3164, "lng": 21.7718, "wiki": "Powiat_kolbuszowski", "siedziba": "Kolbuszowa"},
  {"kod": "RKR", "nazwa": "powiat krośnieński", "typ": "ziemski", "woj": "podkarpackie", "lat": 49.5949, "lng": 21.7621, "wiki": "Powiat_krośnieński", "siedziba": "Krosno"},
  {"kod": "RLS", "nazwa": "powiat leski", "typ": "ziemski", "woj": "podkarpackie", "lat": 49.3199, "lng": 22.3552, "wiki": "Powiat_leski", "siedziba": "Lesko"},
  {"kod": "RLE", "nazwa": "powiat leżajski", "typ": "ziemski", "woj": "podkarpackie", "lat": 50.2615, "lng": 22.4142, "wiki": "Powiat_leżajski", "siedziba": "Leżajsk"},
  {"kod": "RLU", "nazwa": "powiat lubaczowski", "typ": "ziemski", "woj": "podkarpackie", "lat": 50.1957, "lng": 23.1453, "wiki": "Powiat_lubaczowski", "siedziba": "Lubaczów"},
  {"kod": "RMI", "nazwa": "powiat mielecki", "typ": "ziemski", "woj": "podkarpackie", "lat": 50.3139, "lng": 21.3977, "wiki": "Powiat_mielecki", "siedziba": "Mielec"},
  {"kod": "RNI", "nazwa": "powiat niżański", "typ": "ziemski", "woj": "podkarpackie", "lat": 50.4642, "lng": 22.2689, "wiki": "Powiat_niżański", "siedziba": "Nisko"},
  {"kod": "RPR", "nazwa": "powiat przemyski", "typ": "ziemski", "woj": "podkarpackie", "lat": 49.7614, "lng": 22.5222, "wiki": "Powiat_przemyski", "siedziba": "Przemyśl"},
  {"kod": "RPZ", "nazwa": "powiat przeworski", "typ": "ziemski", "woj": "podkarpackie", "lat": 50.0892, "lng": 22.4869, "wiki": "Powiat_przeworski", "siedziba": "Przeworsk"},
  {"kod": "RRS", "nazwa": "powiat ropczycko-sędziszowski", "typ": "ziemski", "woj": "podkarpackie", "lat": 50.0481, "lng": 21.6509, "wiki": "Powiat_ropczycko-sędziszowski", "siedziba": "Ropczyce"},
  {"kod": "RZE", "nazwa": "powiat rzeszowski", "typ": "ziemski", "woj": "podkarpackie", "lat": 50.0575, "lng": 21.8608, "wiki": "Powiat_rzeszowski", "siedziba": "Rzeszów"},
  {"kod": "RSA", "nazwa": "powiat sanocki", "typ": "ziemski", "woj": "podkarpackie", "lat": 49.4299, "lng": 22.1013, "wiki": "Powiat_sanocki", "siedziba": "Sanok"},
  {"kod": "RST", "nazwa": "powiat stalowowolski", "typ": "ziemski", "woj": "podkarpackie", "lat": 50.591, "lng": 22.0918, "wiki": "Powiat_stalowowolski", "siedziba": "Stalowa Wola"},
  {"kod": "RSR", "nazwa": "powiat strzyżowski", "typ": "ziemski", "woj": "podkarpackie", "lat": 49.877, "lng": 21.7157, "wiki": "Powiat_strzyżowski", "siedziba": "Strzyżów"},
  {"kod": "RTA", "nazwa": "powiat tarnobrzeski", "typ": "ziemski", "woj": "podkarpackie", "lat": 50.5627, "lng": 21.8603, "wiki": "Powiat_tarnobrzeski", "siedziba": "Tarnobrzeg"},
  {"kod": "RLA", "nazwa": "powiat łańcucki", "typ": "ziemski", "woj": "podkarpackie", "lat": 50.0866, "lng": 22.2746, "wiki": "Powiat_łańcucki", "siedziba": "Łańcut"},
  // ========== ŚLĄSKIE ==========
  {"kod": "SB", "nazwa": "Bielsko-Biała", "typ": "miasto", "woj": "śląskie", "lat": 49.8121, "lng": 19.0292, "wiki": "Bielsko-Biała"},
  {"kod": "SY", "nazwa": "Bytom", "typ": "miasto", "woj": "śląskie", "lat": 50.3653, "lng": 18.8722, "wiki": "Bytom"},
  {"kod": "SH", "nazwa": "Chorzów", "typ": "miasto", "woj": "śląskie", "lat": 50.2886, "lng": 18.9704, "wiki": "Chorzów"},
  {"kod": "SC", "nazwa": "Częstochowa", "typ": "miasto", "woj": "śląskie", "lat": 50.8097, "lng": 19.1245, "wiki": "Częstochowa"},
  {"kod": "SD", "nazwa": "Dąbrowa Górnicza", "typ": "miasto", "woj": "śląskie", "lat": 50.3698, "lng": 19.2889, "wiki": "Dąbrowa_Górnicza"},
  {"kod": "SG", "nazwa": "Gliwice", "typ": "miasto", "woj": "śląskie", "lat": 50.3011, "lng": 18.6623, "wiki": "Gliwice"},
  {"kod": "SJZ", "nazwa": "Jastrzębie-Zdrój", "typ": "miasto", "woj": "śląskie", "lat": 49.9607, "lng": 18.5996, "wiki": "Jastrzębie-Zdrój"},
  {"kod": "SJ", "nazwa": "Jaworzno", "typ": "miasto", "woj": "śląskie", "lat": 50.1895, "lng": 19.2725, "wiki": "Jaworzno"},
  {"kod": "SK", "nazwa": "Katowice", "typ": "miasto", "woj": "śląskie", "lat": 50.2138, "lng": 19.0059, "wiki": "Katowice"},
  {"kod": "SM", "nazwa": "Mysłowice", "typ": "miasto", "woj": "śląskie", "lat": 50.2096, "lng": 19.1328, "wiki": "Mysłowice"},
  {"kod": "SPI", "nazwa": "Piekary Śląskie", "typ": "miasto", "woj": "śląskie", "lat": 50.3758, "lng": 18.9379, "wiki": "Piekary_Śląskie"},
  {"kod": "SL", "nazwa": "Ruda Śląska", "typ": "miasto", "woj": "śląskie", "lat": 50.27, "lng": 18.8643, "wiki": "Ruda_Śląska"},
  {"kod": "SR", "nazwa": "Rybnik", "typ": "miasto", "woj": "śląskie", "lat": 50.1106, "lng": 18.5532, "wiki": "Rybnik"},
  {"kod": "SI", "nazwa": "Siemianowice Śląskie", "typ": "miasto", "woj": "śląskie", "lat": 50.3123, "lng": 19.0178, "wiki": "Siemianowice_Śląskie"},
  {"kod": "SO", "nazwa": "Sosnowiec", "typ": "miasto", "woj": "śląskie", "lat": 50.2711, "lng": 19.2155, "wiki": "Sosnowiec"},
  {"kod": "SW", "nazwa": "Świętochłowice", "typ": "miasto", "woj": "śląskie", "lat": 50.298, "lng": 18.9064, "wiki": "Świętochłowice"},
  {"kod": "ST", "nazwa": "Tychy", "typ": "miasto", "woj": "śląskie", "lat": 50.1265, "lng": 19.0068, "wiki": "Tychy"},
  {"kod": "SZ", "nazwa": "Zabrze", "typ": "miasto", "woj": "śląskie", "lat": 50.3144, "lng": 18.7816, "wiki": "Zabrze"},
  {"kod": "SZO", "nazwa": "Żory", "typ": "miasto", "woj": "śląskie", "lat": 50.0389, "lng": 18.6806, "wiki": "Żory"},
  {"kod": "SBE", "nazwa": "powiat będziński", "typ": "ziemski", "woj": "śląskie", "lat": 50.4154, "lng": 19.113, "wiki": "Powiat_będziński", "siedziba": "Będzin"},
  {"kod": "SBI", "nazwa": "powiat bielski", "typ": "ziemski", "woj": "śląskie", "lat": 49.8058, "lng": 18.9093, "wiki": "Powiat_bielski", "siedziba": "Bielsko-Biała"},
  {"kod": "SBL", "nazwa": "powiat bieruńsko-lędziński", "typ": "ziemski", "woj": "śląskie", "lat": 50.0934, "lng": 19.141, "wiki": "Powiat_bieruńsko-lędziński", "siedziba": "Bieruń"},
  {"kod": "SCI", "nazwa": "powiat cieszyński", "typ": "ziemski", "woj": "śląskie", "lat": 49.7262, "lng": 18.8102, "wiki": "Powiat_cieszyński", "siedziba": "Cieszyn"},
  {"kod": "SCZ", "nazwa": "powiat częstochowski", "typ": "ziemski", "woj": "śląskie", "lat": 50.8411, "lng": 19.5053, "wiki": "Powiat_częstochowski", "siedziba": "Częstochowa"},
  {"kod": "SGL", "nazwa": "powiat gliwicki", "typ": "ziemski", "woj": "śląskie", "lat": 50.3627, "lng": 18.4855, "wiki": "Powiat_gliwicki", "siedziba": "Gliwice"},
  {"kod": "SKL", "nazwa": "powiat kłobucki", "typ": "ziemski", "woj": "śląskie", "lat": 50.9327, "lng": 18.8656, "wiki": "Powiat_kłobucki", "siedziba": "Kłobuck"},
  {"kod": "SLU", "nazwa": "powiat lubliniecki", "typ": "ziemski", "woj": "śląskie", "lat": 50.6737, "lng": 18.7465, "wiki": "Powiat_lubliniecki", "siedziba": "Lubliniec"},
  {"kod": "SMI", "nazwa": "powiat mikołowski", "typ": "ziemski", "woj": "śląskie", "lat": 50.151, "lng": 18.8307, "wiki": "Powiat_mikołowski", "siedziba": "Mikołów"},
  {"kod": "SMY", "nazwa": "powiat myszkowski", "typ": "ziemski", "woj": "śląskie", "lat": 50.6055, "lng": 19.2948, "wiki": "Powiat_myszkowski", "siedziba": "Myszków"},
  {"kod": "SPS", "nazwa": "powiat pszczyński", "typ": "ziemski", "woj": "śląskie", "lat": 49.9901, "lng": 18.8912, "wiki": "Powiat_pszczyński", "siedziba": "Pszczyna"},
  {"kod": "SRC", "nazwa": "powiat raciborski", "typ": "ziemski", "woj": "śląskie", "lat": 50.087, "lng": 18.2, "wiki": "Powiat_raciborski", "siedziba": "Racibórz"},
  {"kod": "SRB", "nazwa": "powiat rybnicki", "typ": "ziemski", "woj": "śląskie", "lat": 50.1135, "lng": 18.3899, "wiki": "Powiat_rybnicki", "siedziba": "Rybnik"},
  {"kod": "STA", "nazwa": "powiat tarnogórski", "typ": "ziemski", "woj": "śląskie", "lat": 50.4727, "lng": 18.8795, "wiki": "Powiat_tarnogórski", "siedziba": "Tarnowskie Góry"},
  {"kod": "SWD", "nazwa": "powiat wodzisławski", "typ": "ziemski", "woj": "śląskie", "lat": 49.9933, "lng": 18.444, "wiki": "Powiat_wodzisławski", "alt": ["SWZ"], "siedziba": "Wodzisław Śląski"},
  {"kod": "SZA", "nazwa": "powiat zawierciański", "typ": "ziemski", "woj": "śląskie", "lat": 50.5442, "lng": 19.6196, "wiki": "Powiat_zawierciański", "siedziba": "Zawiercie"},
  {"kod": "SZY", "nazwa": "powiat żywiecki", "typ": "ziemski", "woj": "śląskie", "lat": 49.6115, "lng": 19.2277, "wiki": "Powiat_żywiecki", "siedziba": "Żywiec"},
  // ========== ŚWIĘTOKRZYSKIE ==========
  {"kod": "TK", "nazwa": "Kielce", "typ": "miasto", "woj": "świętokrzyskie", "lat": 50.8542, "lng": 20.6099, "wiki": "Kielce"},
  {"kod": "TBU", "nazwa": "powiat buski", "typ": "ziemski", "woj": "świętokrzyskie", "lat": 50.4558, "lng": 20.799, "wiki": "Powiat_buski", "siedziba": "Busko-Zdrój"},
  {"kod": "TJE", "nazwa": "powiat jędrzejowski", "typ": "ziemski", "woj": "świętokrzyskie", "lat": 50.6568, "lng": 20.2963, "wiki": "Powiat_jędrzejowski", "siedziba": "Jędrzejów"},
  {"kod": "TKA", "nazwa": "powiat kazimierski", "typ": "ziemski", "woj": "świętokrzyskie", "lat": 50.2882, "lng": 20.5252, "wiki": "Powiat_kazimierski", "siedziba": "Kazimierza Wielka"},
  {"kod": "TKI", "nazwa": "powiat kielecki", "typ": "ziemski", "woj": "świętokrzyskie", "lat": 50.8015, "lng": 20.8814, "wiki": "Powiat_kielecki", "siedziba": "Kielce"},
  {"kod": "TKN", "nazwa": "powiat konecki", "typ": "ziemski", "woj": "świętokrzyskie", "lat": 51.1516, "lng": 20.3461, "wiki": "Powiat_konecki", "siedziba": "Końskie"},
  {"kod": "TOP", "nazwa": "powiat opatowski", "typ": "ziemski", "woj": "świętokrzyskie", "lat": 50.879, "lng": 21.6659, "wiki": "Powiat_opatowski", "siedziba": "Opatów"},
  {"kod": "TOS", "nazwa": "powiat ostrowiecki", "typ": "ziemski", "woj": "świętokrzyskie", "lat": 50.9424, "lng": 21.3946, "wiki": "Powiat_ostrowiecki", "siedziba": "Ostrowiec Świętokrzyski"},
  {"kod": "TPI", "nazwa": "powiat pińczowski", "typ": "ziemski", "woj": "świętokrzyskie", "lat": 50.4997, "lng": 20.4937, "wiki": "Powiat_pińczowski", "siedziba": "Pińczów"},
  {"kod": "TSA", "nazwa": "powiat sandomierski", "typ": "ziemski", "woj": "świętokrzyskie", "lat": 50.6951, "lng": 21.6799, "wiki": "Powiat_sandomierski", "siedziba": "Sandomierz"},
  {"kod": "TSK", "nazwa": "powiat skarżyski", "typ": "ziemski", "woj": "świętokrzyskie", "lat": 51.0652, "lng": 20.7599, "wiki": "Powiat_skarżyski", "siedziba": "Skarżysko-Kamienna"},
  {"kod": "TST", "nazwa": "powiat starachowicki", "typ": "ziemski", "woj": "świętokrzyskie", "lat": 51.0537, "lng": 21.146, "wiki": "Powiat_starachowicki", "siedziba": "Starachowice"},
  {"kod": "TSZ", "nazwa": "powiat staszowski", "typ": "ziemski", "woj": "świętokrzyskie", "lat": 50.5174, "lng": 21.3063, "wiki": "Powiat_staszowski", "siedziba": "Staszów"},
  {"kod": "TLW", "nazwa": "powiat włoszczowski", "typ": "ziemski", "woj": "świętokrzyskie", "lat": 50.832, "lng": 19.9747, "wiki": "Powiat_włoszczowski", "siedziba": "Włoszczowa"},
  // ========== MAZOWIECKIE ==========
  {"kod": "WO", "nazwa": "Ostrołęka", "typ": "miasto", "woj": "mazowieckie", "lat": 53.0778, "lng": 21.5748, "wiki": "Ostrołęka"},
  {"kod": "WP", "nazwa": "Płock", "typ": "miasto", "woj": "mazowieckie", "lat": 52.5354, "lng": 19.7137, "wiki": "Płock"},
  {"kod": "WR", "nazwa": "Radom", "typ": "miasto", "woj": "mazowieckie", "lat": 51.4173, "lng": 21.161, "wiki": "Radom"},
  {"kod": "WS", "nazwa": "Siedlce", "typ": "miasto", "woj": "mazowieckie", "lat": 52.1616, "lng": 22.2813, "wiki": "Siedlce"},
  {"kod": "WB", "nazwa": "Warszawa - Bemowo", "typ": "miasto", "woj": "mazowieckie", "lat": 52.25, "lng": 20.91, "wiki": "Bemowo"},
  {"kod": "WA", "nazwa": "Warszawa - Białołęka", "typ": "miasto", "woj": "mazowieckie", "lat": 52.3211, "lng": 20.97, "wiki": "Białołęka"},
  {"kod": "WD", "nazwa": "Warszawa - Bielany", "typ": "miasto", "woj": "mazowieckie", "lat": 52.29, "lng": 20.94, "wiki": "Bielany"},
  {"kod": "WE", "nazwa": "Warszawa - Mokotów", "typ": "miasto", "woj": "mazowieckie", "lat": 52.19, "lng": 21.04, "wiki": "Mokotów"},
  {"kod": "WU", "nazwa": "Warszawa - Ochota", "typ": "miasto", "woj": "mazowieckie", "lat": 52.205, "lng": 20.97, "wiki": "Ochota"},
  {"kod": "WH", "nazwa": "Warszawa - Praga Północ", "typ": "miasto", "woj": "mazowieckie", "lat": 52.24, "lng": 21.09, "wiki": "Praga_-Północ"},
  {"kod": "WF", "nazwa": "Warszawa - Praga Południe", "typ": "miasto", "woj": "mazowieckie", "lat": 52.24, "lng": 21.09, "wiki": "Praga_-Południe"},
  {"kod": "WW", "nazwa": "Warszawa - Rembertów, Wilanów, Włochy", "typ": "miasto", "woj": "mazowieckie", "lat": 52.2297, "lng": 21.0122, "wiki": "Rembertów"},
  {"kod": "WI", "nazwa": "Warszawa - Śródmieście", "typ": "miasto", "woj": "mazowieckie", "lat": 52.2297, "lng": 21.0122, "wiki": "Śródmieście"},
  {"kod": "WJ", "nazwa": "Warszawa - Targówek", "typ": "miasto", "woj": "mazowieckie", "lat": 52.29, "lng": 21.07, "wiki": "Targówek"},
  {"kod": "WK", "nazwa": "Warszawa - Ursus", "typ": "miasto", "woj": "mazowieckie", "lat": 52.195, "lng": 20.885, "wiki": "Ursus"},
  {"kod": "WN", "nazwa": "Warszawa - Ursynów", "typ": "miasto", "woj": "mazowieckie", "lat": 52.15, "lng": 21.05, "wiki": "Ursynów"},
  {"kod": "WT", "nazwa": "Warszawa - Wawer", "typ": "miasto", "woj": "mazowieckie", "lat": 52.2, "lng": 21.15, "wiki": "Wawer"},
  {"kod": "WX", "nazwa": "Warszawa - Wesoła, Żoliborz", "typ": "miasto", "woj": "mazowieckie", "lat": 52.2297, "lng": 21.0122, "wiki": "Wesoła"},
  {"kod": "WY", "nazwa": "Warszawa - Wola", "typ": "miasto", "woj": "mazowieckie", "lat": 52.237, "lng": 20.97, "wiki": "Wola"},
  {"kod": "WBR", "nazwa": "powiat białobrzeski", "typ": "ziemski", "woj": "mazowieckie", "lat": 51.621, "lng": 20.9676, "wiki": "Powiat_białobrzeski", "siedziba": "Białobrzegi"},
  {"kod": "WCI", "nazwa": "powiat ciechanowski", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.9023, "lng": 20.6277, "wiki": "Powiat_ciechanowski", "siedziba": "Ciechanów"},
  {"kod": "WG", "nazwa": "powiat garwoliński", "typ": "ziemski", "woj": "mazowieckie", "lat": 51.8265, "lng": 21.6531, "wiki": "Powiat_garwoliński", "siedziba": "Garwolin"},
  {"kod": "WGS", "nazwa": "powiat gostyniński", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.3899, "lng": 19.4824, "wiki": "Powiat_gostyniński", "siedziba": "Gostynin"},
  {"kod": "WGM", "nazwa": "powiat grodziski", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.0639, "lng": 20.5996, "wiki": "Powiat_grodziski", "siedziba": "Grodzisk Mazowiecki"},
  {"kod": "WGR", "nazwa": "powiat grójecki", "typ": "ziemski", "woj": "mazowieckie", "lat": 51.7575, "lng": 20.8705, "wiki": "Powiat_grójecki", "siedziba": "Grójec"},
  {"kod": "WKZ", "nazwa": "powiat kozienicki", "typ": "ziemski", "woj": "mazowieckie", "lat": 51.6395, "lng": 21.4019, "wiki": "Powiat_kozienicki", "siedziba": "Kozienice"},
  {"kod": "WL", "nazwa": "powiat legionowski", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.4518, "lng": 20.9374, "wiki": "Powiat_legionowski", "siedziba": "Legionowo"},
  {"kod": "WLI", "nazwa": "powiat lipski", "typ": "ziemski", "woj": "mazowieckie", "lat": 51.159, "lng": 21.5601, "wiki": "Powiat_lipski", "siedziba": "Lipsko"},
  {"kod": "WMA", "nazwa": "powiat makowski", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.9472, "lng": 21.2528, "wiki": "Powiat_makowski", "siedziba": "Maków Mazowiecki"},
  {"kod": "WM", "nazwa": "powiat miński", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.1842, "lng": 21.6537, "wiki": "Powiat_miński", "siedziba": "Mińsk Mazowiecki"},
  {"kod": "WML", "nazwa": "powiat mławski", "typ": "ziemski", "woj": "mazowieckie", "lat": 53.055, "lng": 20.3222, "wiki": "Powiat_mławski", "siedziba": "Mława"},
  {"kod": "WND", "nazwa": "powiat nowodworski", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.4657, "lng": 20.6675, "wiki": "Powiat_nowodworski", "siedziba": "Nowy Dwór Mazowiecki"},
  {"kod": "WOR", "nazwa": "powiat ostrowski", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.7951, "lng": 21.9887, "wiki": "Powiat_ostrowski", "siedziba": "Ostrów Mazowiecka"},
  {"kod": "WOS", "nazwa": "powiat ostrołęcki", "typ": "ziemski", "woj": "mazowieckie", "lat": 53.1401, "lng": 21.4524, "wiki": "Powiat_ostrołęcki", "siedziba": "Ostrołęka"},
  {"kod": "WOT", "nazwa": "powiat otwocki", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.0486, "lng": 21.3964, "wiki": "Powiat_otwocki", "siedziba": "Otwock"},
  {"kod": "WPI", "nazwa": "powiat piaseczyński", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.0163, "lng": 21.0144, "wiki": "Powiat_piaseczyński", "siedziba": "Piaseczno"},
  {"kod": "WPR", "nazwa": "powiat pruszkowski", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.1009, "lng": 20.8407, "wiki": "Powiat_pruszkowski", "alt": ["WPP", "WPS"], "siedziba": "Pruszków"},
  {"kod": "WPZ", "nazwa": "powiat przasnyski", "typ": "ziemski", "woj": "mazowieckie", "lat": 53.1136, "lng": 20.9134, "wiki": "Powiat_przasnyski", "siedziba": "Przasnysz"},
  {"kod": "WPY", "nazwa": "powiat przysuski", "typ": "ziemski", "woj": "mazowieckie", "lat": 51.4237, "lng": 20.63, "wiki": "Powiat_przysuski", "siedziba": "Przysucha"},
  {"kod": "WPU", "nazwa": "powiat pułtuski", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.6718, "lng": 20.9917, "wiki": "Powiat_pułtuski", "siedziba": "Pułtusk"},
  {"kod": "WPL", "nazwa": "powiat płocki", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.5547, "lng": 19.966, "wiki": "Powiat_płocki", "siedziba": "Płock"},
  {"kod": "WPN", "nazwa": "powiat płoński", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.6391, "lng": 20.4323, "wiki": "Powiat_płoński", "siedziba": "Płońsk"},
  {"kod": "WRA", "nazwa": "powiat radomski", "typ": "ziemski", "woj": "mazowieckie", "lat": 51.3359, "lng": 21.1922, "wiki": "Powiat_radomski", "siedziba": "Radom"},
  {"kod": "WSI", "nazwa": "powiat siedlecki", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.1919, "lng": 22.4531, "wiki": "Powiat_siedlecki", "siedziba": "Siedlce"},
  {"kod": "WSE", "nazwa": "powiat sierpecki", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.8336, "lng": 19.6919, "wiki": "Powiat_sierpecki", "siedziba": "Sierpc"},
  {"kod": "WSC", "nazwa": "powiat sochaczewski", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.267, "lng": 20.1532, "wiki": "Powiat_sochaczewski", "siedziba": "Sochaczew"},
  {"kod": "WSK", "nazwa": "powiat sokołowski", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.4952, "lng": 22.3207, "wiki": "Powiat_sokołowski", "siedziba": "Sokołów Podlaski"},
  {"kod": "WSZ", "nazwa": "powiat szydłowiecki", "typ": "ziemski", "woj": "mazowieckie", "lat": 51.2561, "lng": 20.8439, "wiki": "Powiat_szydłowiecki", "siedziba": "Szydłowiec"},
  {"kod": "WZ", "nazwa": "powiat warszawski zachodni", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.2682, "lng": 20.6084, "wiki": "Powiat_warszawski_zachodni", "siedziba": "Ożarów Mazowiecki"},
  {"kod": "WWE", "nazwa": "powiat węgrowski", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.4562, "lng": 21.9461, "wiki": "Powiat_węgrowski", "siedziba": "Węgrów"},
  {"kod": "WV", "nazwa": "powiat wołomiński", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.4061, "lng": 21.4163, "wiki": "Powiat_wołomiński", "alt": ["WWL"], "siedziba": "Wołomin"},
  {"kod": "WWY", "nazwa": "powiat wyszkowski", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.6508, "lng": 21.5107, "wiki": "Powiat_wyszkowski", "siedziba": "Wyszków"},
  {"kod": "WZU", "nazwa": "powiat żuromiński", "typ": "ziemski", "woj": "mazowieckie", "lat": 53.0166, "lng": 19.878, "wiki": "Powiat_żuromiński", "siedziba": "Żuromin"},
  {"kod": "WZW", "nazwa": "powiat zwoleński", "typ": "ziemski", "woj": "mazowieckie", "lat": 51.3608, "lng": 21.6423, "wiki": "Powiat_zwoleński", "siedziba": "Zwoleń"},
  {"kod": "WZY", "nazwa": "powiat żyrardowski", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.0002, "lng": 20.4367, "wiki": "Powiat_żyrardowski", "siedziba": "Żyrardów"},
  {"kod": "WLS", "nazwa": "powiat łosicki", "typ": "ziemski", "woj": "mazowieckie", "lat": 52.2237, "lng": 22.8375, "wiki": "Powiat_łosicki", "siedziba": "Łosice"},
  // ========== ZACHODNIOPOMORSKIE ==========
  {"kod": "ZK", "nazwa": "Koszalin", "typ": "miasto", "woj": "zachodniopomorskie", "lat": 54.2073, "lng": 16.2175, "wiki": "Koszalin"},
  {"kod": "ZSW", "nazwa": "Świnoujście", "typ": "miasto", "woj": "zachodniopomorskie", "lat": 53.847, "lng": 14.3259, "wiki": "Świnoujście"},
  {"kod": "ZS", "nazwa": "Szczecin", "typ": "miasto", "woj": "zachodniopomorskie", "lat": 53.4298, "lng": 14.5929, "wiki": "Szczecin", "alt": ["ZZ"]},
  {"kod": "ZBI", "nazwa": "powiat białogardzki", "typ": "ziemski", "woj": "zachodniopomorskie", "lat": 53.9769, "lng": 16.0549, "wiki": "Powiat_białogardzki", "siedziba": "Białogard"},
  {"kod": "ZCH", "nazwa": "powiat choszczeński", "typ": "ziemski", "woj": "zachodniopomorskie", "lat": 53.1427, "lng": 15.6501, "wiki": "Powiat_choszczeński", "siedziba": "Choszczno"},
  {"kod": "ZDR", "nazwa": "powiat drawski", "typ": "ziemski", "woj": "zachodniopomorskie", "lat": 53.4475, "lng": 16.0404, "wiki": "Powiat_drawski", "siedziba": "Drawsko Pomorskie"},
  {"kod": "ZGL", "nazwa": "powiat goleniowski", "typ": "ziemski", "woj": "zachodniopomorskie", "lat": 53.6103, "lng": 14.8973, "wiki": "Powiat_goleniowski", "siedziba": "Goleniów"},
  {"kod": "ZGY", "nazwa": "powiat gryficki", "typ": "ziemski", "woj": "zachodniopomorskie", "lat": 53.9429, "lng": 15.2602, "wiki": "Powiat_gryficki", "siedziba": "Gryfice"},
  {"kod": "ZGR", "nazwa": "powiat gryfiński", "typ": "ziemski", "woj": "zachodniopomorskie", "lat": 53.0229, "lng": 14.5058, "wiki": "Powiat_gryfiński", "siedziba": "Gryfino"},
  {"kod": "ZKA", "nazwa": "powiat kamieński", "typ": "ziemski", "woj": "zachodniopomorskie", "lat": 53.9109, "lng": 14.7123, "wiki": "Powiat_kamieński", "siedziba": "Kamień Pomorski"},
  {"kod": "ZKO", "nazwa": "powiat koszaliński", "typ": "ziemski", "woj": "zachodniopomorskie", "lat": 54.1097, "lng": 16.4399, "wiki": "Powiat_koszaliński", "siedziba": "Koszalin"},
  {"kod": "ZKL", "nazwa": "powiat kołobrzeski", "typ": "ziemski", "woj": "zachodniopomorskie", "lat": 54.0499, "lng": 15.5997, "wiki": "Powiat_kołobrzeski", "siedziba": "Kołobrzeg"},
  {"kod": "ZMY", "nazwa": "powiat myśliborski", "typ": "ziemski", "woj": "zachodniopomorskie", "lat": 52.855, "lng": 14.7754, "wiki": "Powiat_myśliborski", "siedziba": "Myślibórz"},
  {"kod": "ZPL", "nazwa": "powiat policki", "typ": "ziemski", "woj": "zachodniopomorskie", "lat": 53.5298, "lng": 14.4368, "wiki": "Powiat_policki", "siedziba": "Police"},
  {"kod": "ZPY", "nazwa": "powiat pyrzycki", "typ": "ziemski", "woj": "zachodniopomorskie", "lat": 53.1276, "lng": 14.9702, "wiki": "Powiat_pyrzycki", "siedziba": "Pyrzyce"},
  {"kod": "ZST", "nazwa": "powiat stargardzki", "typ": "ziemski", "woj": "zachodniopomorskie", "lat": 53.3152, "lng": 15.1651, "wiki": "Powiat_stargardzki", "siedziba": "Stargard"},
  {"kod": "ZSD", "nazwa": "powiat świdwiński", "typ": "ziemski", "woj": "zachodniopomorskie", "lat": 53.8075, "lng": 15.8823, "wiki": "Powiat_świdwiński", "siedziba": "Świdwin"},
  {"kod": "ZSZ", "nazwa": "powiat szczecinecki", "typ": "ziemski", "woj": "zachodniopomorskie", "lat": 53.7377, "lng": 16.5597, "wiki": "Powiat_szczecinecki", "siedziba": "Szczecinek"},
  {"kod": "ZSL", "nazwa": "powiat sławieński", "typ": "ziemski", "woj": "zachodniopomorskie", "lat": 54.379, "lng": 16.5825, "wiki": "Powiat_sławieński", "siedziba": "Sławno"},
  {"kod": "ZWA", "nazwa": "powiat wałecki", "typ": "ziemski", "woj": "zachodniopomorskie", "lat": 53.2365, "lng": 16.319, "wiki": "Powiat_wałecki", "siedziba": "Wałcz"},
  {"kod": "ZLO", "nazwa": "powiat łobeski", "typ": "ziemski", "woj": "zachodniopomorskie", "lat": 53.6729, "lng": 15.5162, "wiki": "Powiat_łobeski", "siedziba": "Łobez"},
];
