const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function setup(){const db=new Map(),ctx={window:{},document:{addEventListener(){}},localStorage:{getItem:k=>db.get(k)||null,setItem:(k,v)=>db.set(k,v)},navigator:{},fetch:async u=>({ok:true,json:async()=>u==='baza.json'?JSON.parse(fs.readFileSync('baza.json')):u==='karty-dane.json'&&fs.existsSync(u)?JSON.parse(fs.readFileSync(u)):{}})};vm.createContext(ctx);vm.runInContext(fs.readFileSync('karty.js','utf8'),ctx);vm.runInContext(fs.readFileSync('karta-w-ciemno-zasady.js','utf8'),ctx);return {M:ctx.window.KartyModel,K:ctx.window.Karty,Z:ctx.window.CiemnoZasady,db};}
function rows(M){return Array.from({length:202},(_,i)=>{const type=i<101?'gmina wiejska':'gmina miejska',v=i%101;return {k:String(1000000+i),n:'Gmina '+i,typ:type,woj:i%2?'A':'B',...Object.fromEntries(M.STATY.map(s=>[s.k,s.t==='o'?101-v:v+1]))};});}
test('OVR osobno: silna wieś i silne miasto 90+, większość 55–75',()=>{const {M}=setup(),g=rows(M);M.calculate(g,'2025');for(const group of ['wies','miasto']){const a=g.filter(x=>x.grupa===group);assert.equal(Math.max(...a.map(x=>x.ovr)),94);assert.equal(Math.min(...a.map(x=>x.ovr)),40);assert.ok(a.filter(x=>x.ovr>=90).length<=4);assert.ok(a.filter(x=>x.ovr>=55&&x.ovr<=75).length>50);}assert.equal(M.grupa({typ:'gmina miejsko-wiejska'}),'miasto');});
test('Remisy statystyk i rekordów niezależne od kolejności; braki nie są zerami',()=>{const {M}=setup(),g=rows(M);g[1].ludnosc=g[0].ludnosc;g[2].ludnosc=null;M.calculate(g,'2025');assert.equal(g[0].oc.ludnosc,g[1].oc.ludnosc);assert.equal(g[2].oc.ludnosc,undefined);assert.ok(g[0].rekordy.some(r=>r.k==='ludnosc'&&r.dir==='min'));assert.ok(g[1].rekordy.some(r=>r.k==='ludnosc'&&r.dir==='min'));assert.ok(!g[2].rekordy.some(r=>r.k==='ludnosc'));const copy=structuredClone(g).reverse();M.calculate(copy,'2025');for(const a of g)assert.equal(a.oc.ludnosc,copy.find(b=>b.k===a.k).oc.ludnosc);});
test('Wagi miejskie i wiejskie oraz wstrzymane szkoły',()=>{const {M}=setup(),g=rows(M);M.calculate(g,'2025');const get=k=>M.STATY.find(s=>s.k===k);assert.equal(get('pit_na_mieszk').miasto,2);assert.equal(get('pit_na_mieszk').wies,0);assert.equal(get('wodociag_proc').miasto,0);assert.equal(get('szkoly_na_1000').wies,1);delete g[0].szkoly_na_1000;M.calculate(g,'2025');assert.equal(g[0].ovr,null);M.calculate(g,'2025',['szkoly_na_1000']);assert.notEqual(g[0].ovr,null);});
test('Premia: pełny powiat i 40 trafień = +5, limit wskaźnika 99',()=>{const {M}=setup(),g=[{k:'1234012'},{k:'1234022'}],owned=new Set(g.map(x=>x.k));for(const [hits,expected] of [[0,1],[9,1],[10,2],[27,3],[39,4],[40,5],[99,5]])assert.equal(M.upgrade(g[0],g,owned,{['kontur:'+g[0].k]:{ok:hits}}).bonus,expected);assert.equal(M.upgrade(g[0],g,new Set([g[0].k]),{['kontur:'+g[0].k]:{ok:40}}).bonus,4);assert.equal(M.score({oc:{x:94},rekordy:[{k:'x'}]},'x',5,true),99);});
test('Migracja v3 zachowuje nieogłoszone karty z dotychczasowych progów',async()=>{const {K,db}=setup();await K.zaladuj();const g=K.dane().g.find(g=>g._staryProg<K.prog(g));assert.ok(g);db.set('karty-zasady','3');db.set('nauka-v1',JSON.stringify({['gmina:'+g.k]:{ok:g._staryProg}}));K.migracja();assert.ok(K.zdobyte().mam.has(g.k));assert.equal(db.get('karty-zasady'),'4');});
test('Rekordy: dwa krajowe = legenda; równy wskaźnik nie tworzy rekordu',()=>{const {M}=setup(),g=rows(M);M.calculate(g,'2025');assert.ok(g.some(x=>x.rz==='legenda'));g.forEach(x=>x.wodociag_proc=100);M.calculate(g,'2025');assert.ok(g.every(x=>!x.rekordy.some(r=>r.k==='wodociag_proc')));});
test('Karta w ciemno: 5 różnych wskaźników, top12 losowo, karta odpada',()=>{const {Z}=setup(),deck=Array.from({length:20},(_,i)=>({k:String(i),oc:{x:40+i},ovr:60,bonus:0,rekordy:[]}));const used=new Set(['19']);const c=Z.candidates(deck,used,'x',Z.seeded(5));assert.equal(c.length,12);assert.ok(c.every(x=>+x.k>=7&&x.k!=='19'));assert.notDeepEqual(c.map(x=>x.k),[...c].sort((a,b)=>+b.k-+a.k).map(x=>x.k));assert.equal(new Set(Z.shuffle(Array.from({length:11},(_,i)=>i),Z.seeded(3)).slice(0,5)).size,5);});
test('Runda: oceny, bonus, remis OVR, punkt za optymalny wybór obu stron',()=>{const {Z}=setup(),a={k:'a',oc:{x:70},ovr:70,bonus:2,rekordy:[]},b={k:'b',oc:{x:72},ovr:65,bonus:0,rekordy:[]};const r=Z.resolve(a,b,[a],[b],'x');assert.equal(r.winner,0);assert.deepEqual([...r.points],[2,1]);b.ovr=72;assert.equal(Z.resolve(a,b,[a],[b],'x').winner,null);assert.throws(()=>Z.resolve(a,b,[],[b],'x'));});
test('Pożyczone karty tylko do 12, równa talia bez ulepszeń',()=>{const {M,Z}=setup(),all=rows(M);M.calculate(all,'2025');const region='A',owned=new Set([all[1].k]),a=Z.deck(all,owned,region,false,Z.seeded(1),()=>5);assert.equal(a.length,12);assert.equal(a.filter(x=>x.borrowed).length,11);assert.equal(owned.size,1);const eq=Z.deck(all,owned,region,true,Z.seeded(1),()=>5);assert.equal(eq.length,12);assert.ok(eq.every(x=>x.woj===region&&x.bonus===0&&!x.borrowed));});
test('AI łatwy wybiera górną połowę, trudny najlepszą przy progu',()=>{const {Z}=setup(),a=Array.from({length:12},(_,i)=>({k:String(i),ovr:60,bonus:0,oc:{x:i},rekordy:[]}));assert.ok(+Z.ai(a,'x','easy',()=>.99).k>=6);assert.equal(Z.ai(a,'x','hard',()=>.5).k,'11');});
test('Zestaw rekordzistek: paczka i odznaka tylko raz na edycję',async()=>{const {K,db}=setup();await K.zaladuj();const d=K.dane(),woj=d.g[0].woj,all=d.g.filter(g=>g.woj===woj&&g.rekordy.length);assert.ok(all.length);db.set('nauka-v1',JSON.stringify(Object.fromEntries(all.map(g=>['kontur:'+g.k,{ok:1}]))));K.migracja();assert.equal(Object.keys(K.odznaki()).length,1);assert.equal(K.zetony(),25);K.migracja();K.archiwizuj();assert.equal(K.zetony(),25);db.set('karty-zetony','-25');K.archiwizuj();assert.equal(K.zetony(),0);});
