const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function fixture(){const db=new Map([['karty-zasady','3']]);const ctx={window:{},document:{addEventListener(){}},localStorage:{getItem:k=>db.get(k)||null,setItem:(k,v)=>db.set(k,v)},navigator:{},fetch:async u=>({ok:true,json:async()=>u==='baza.json'?JSON.parse(fs.readFileSync('baza.json')):{}})};vm.createContext(ctx);vm.runInContext(fs.readFileSync('karty.js','utf8'),ctx);return {k:ctx.window.Karty,db};}
test('3/4/5/6/7 fragmentów; kontur zawsze pełna karta',async()=>{const {k,db}=fixture();await k.zaladuj();for(const rz of k.KOLEJ){const g=k.dane().g.find(g=>g.rz===rz),n=k.prog(g);db.set('nauka-v1',JSON.stringify({['gmina:'+g.k]:{ok:n-1}}));assert.equal(k.zdobyte().mam.has(g.k),false);db.set('nauka-v1',JSON.stringify({['gmina:'+g.k]:{ok:n}}));assert.equal(k.zdobyte().mam.has(g.k),true);db.set('nauka-v1',JSON.stringify({['kontur:'+g.k]:{ok:1}}));assert.equal(k.zdobyte().mam.has(g.k),true);}});
test('Migracja zachowuje starą pełną kartę diamentową',async()=>{const {k,db}=fixture();await k.zaladuj();db.set('karty-zasady','2');const g=k.dane().g.find(g=>g.rz==='diament');db.set('nauka-v1',JSON.stringify({['gmina:'+g.k]:{ok:3}}));k.migracja();assert.ok(k.zdobyte().mam.has(g.k));});
test('Paczki i drop mają sumy 100%; lepsze paczki częściej dają rzadkie karty',async()=>{const {k}=fixture();for(const t of [k.PACZKI,...Object.values(k.DROP)])assert.ok(Math.abs(t.reduce((s,[,p])=>s+p,0)-1)<1e-9);assert.equal(k.losuj(k.PACZKI,0),'zwykla');assert.equal(k.losuj(k.PACZKI,.999),'legenda');let last=0;for(const c of ['zwykla','braz','srebro','zloto','diament','legenda']){const p=k.DROP[c].filter(([r])=>['legenda','diament','zloto'].includes(r)).reduce((a,[,v])=>a+v,0);assert.ok(p>last);last=p;}});
test('Nagroda za poziom lub mecz raz, bez podwójnej karty w albumie',async()=>{const {k}=fixture();const p=await k.nagrodaZa('poziom:0');assert.ok(p&&p.paczka);assert.equal(await k.nagrodaZa('poziom:0'),null);const l=await k.otworzPaczke();assert.ok(l.length>=2&&l.length<=7);for(const g of l)assert.ok(k.zdobyte().mam.has(g.k));assert.ok(await k.nagrodaZa('mecz:uuid'));assert.equal(await k.nagrodaZa('mecz:uuid'),null);});
test('Dogrywka tylko przy remisie; nagroda dopiero dla jednego zwycięzcy',()=>{const c={window:{}};vm.createContext(c);vm.runInContext(fs.readFileSync('multiplayer-zasady.js','utf8'),c);const m=c.window.MeczZasady,players=[{id:'a',pts:100},{id:'b',pts:100}];assert.equal(m.remis(players),true);assert.equal(m.zwyciezca(players),null);assert.equal(m.szybki({a:{pts:1000,ms:1500},b:{pts:1000,ms:1100}},['a','b']),'b');assert.equal(m.szybki({a:{pts:0,ms:200}},['a','b']),null);players[1].pts++;assert.equal(m.zwyciezca(players).id,'b');});
test('Paczka: 2–7 różnych kart zależnie od rodzaju, gwarancja rzadkości, najlepsza na koniec',async()=>{const {k}=fixture();await k.zaladuj();const R=k.KOLEJ;for(const [kolor,n] of Object.entries({zwykla:2,braz:3,srebro:4,zloto:5,diament:6,legenda:7})){assert.equal(k.KART_W_PACZCE[kolor],n);for(let p=0;p<20;p++){const l=k.zawartoscPaczki(kolor);assert.equal(l.length,n);assert.equal(new Set(l.map(g=>g.k)).size,n);for(let i=1;i<l.length;i++)assert.ok(R.indexOf(l[i].rz)<=R.indexOf(l[i-1].rz));const min={srebro:'srebro',zloto:'zloto',diament:'diament',legenda:'legenda'}[kolor];if(min)assert.ok(l.some(g=>R.indexOf(g.rz)<=R.indexOf(min)),kolor);}}});
test('Paczka za monety kosztuje 25, duplikat oddaje monety',async()=>{const {k,db}=fixture();await k.zaladuj();db.set('karty-zetony','25');const l=await k.otworzPaczke();assert.ok(l.length>=2);assert.equal(+db.get('karty-zetony'),l.filter(g=>g._duplikat).length*k.DUPLIKAT);assert.equal(await k.otworzPaczke(),null);});
