const {test}=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
function saga(){const db=new Map();const K={nagrodaZa:async()=>null};const ctx={window:{Karty:K},Karty:K,localStorage:{getItem:k=>db.has(k)?db.get(k):null,setItem:(k,v)=>db.set(k,String(v))},Date,Math,JSON};vm.createContext(ctx);vm.runInContext(fs.readFileSync('saga.js','utf8'),ctx);return {S:ctx.window.Saga,db};}
test('Czwarty poziom każdej krainy to osobna gra, zmieniająca się z krainy na krainę',()=>{const {S}=saga();const gry=new Set();for(let s=0;s<S.SWIATY.length;s++){const p=S.poziom(s*6+3,1);assert.ok(p.specjalna);gry.add(p.specjalna);}assert.deepEqual([...gry].sort(),['ciemno','ksztalt','lancuch','mapa']);
 assert.match(S.adres(3,1),/^lancuch\.html\?poziom=3$/);assert.match(S.adres(9,1),/^ksztalt\.html\?rodzaj=g&poziom=9$/);assert.match(S.adres(15,1),/^karta-w-ciemno\.html\?poziom=15$/);assert.match(S.adres(21,1),/tryb=saga&poziom=21$/);assert.equal(S.poziom(21,1).gry[0].t,'g');assert.equal(S.poziom(21,1).czas,15);});
test('Druga plansza: zamknięta do ukończenia pierwszej, trudniejsza i z osobnym zapisem',()=>{const {S,db}=saga();assert.equal(S.odblokowany(0,null,2),false);S.ustawSezon(2);assert.equal(S.sezon(),1);
 const gw={};for(let n=0;n<S.ILE;n++)gw[n]=S.poziom(n,1).boss?2:1;db.set('saga-v1',JSON.stringify({gw,wynik:{}}));assert.equal(S.ukonczona(1),true);assert.equal(S.sezon(),2);assert.equal(S.odblokowany(0,null,2),true);assert.equal(S.odblokowany(1,null,2),false);
 const p=S.poziom(0,2);assert.equal(p.podp,false);assert.equal(p.czas,15);assert.match(S.adres(0,2),/sezon=2/);S.zapisz(0,3,5000,2);assert.equal(S.stan(2).gw[0],3);assert.equal(S.stan(1).gw[0],1);assert.notEqual(S.poziom(3,2).specjalna,S.poziom(3,1).specjalna);});
test('Wydarzenie tygodnia: tydzień ISO, punkty poziomu raz lepsze, premia raz na tydzień',()=>{const {S,db}=saga();const T=S.tydzien(new Date('2026-10-10T12:00:00'));assert.equal(T.klucz,'2026-W41');assert.equal(S.tydzien(new Date('2027-01-03T12:00:00')).klucz,'2026-W53');
 const t=S.tydzien(),n=t.kraina*6;db.set('karty-zetony','0');const r1=S.zakoncz({n,sezon:1,gw:2,wynik:4000,proc:60});assert.equal(r1.wyd.pkt,260);assert.equal(db.get('karty-zetony'),'5');
 const r2=S.zakoncz({n,sezon:1,gw:1,wynik:1000,proc:35});assert.equal(r2.wyd.suma,260);assert.equal(db.get('karty-zetony'),'5');const inna=((t.kraina+1)%16)*6;assert.equal(S.zakoncz({n:inna,sezon:1,gw:3,wynik:1,proc:90}).wyd,null);});
